require "digest"
require "open3"
require "rspec"
require "tmpdir"

require_relative "../ruby/tools/c_ffi_generator"

RSpec.describe CFFIGenerator do
  around do |example|
    Dir.mktmpdir("clear-c-ffi-generator") do |directory|
      @directory = directory
      @header = File.join(directory, "fixture.h")
      @output = File.join(directory, "fixture.ffi.clear")
      File.write(@header, <<~HEADER)
        typedef struct fixture_handle fixture_handle;
        typedef struct fixture_pair { int id; double weight; } fixture_pair;
        typedef int (*fixture_callback)(int value);
        int fixture_open(const char *name, fixture_handle **out);
        int fixture_apply(int value, fixture_callback callback);
      HEADER
      example.run
    end
  end

  it "generates portable declarations and delegates canonical layout to clear fmt" do
    content = described_class.generate(header: @header, output: @output, library: "fixture")

    expect(content).to start_with("# Generated by clear c-ffi.")
    expect(content).to include("# Source: fixture.h")
    expect(content).to include("# Header-SHA256: #{Digest::SHA256.file(@header).hexdigest}")
    expect(content).to include("EXTERN STRUCT FixtureHandle {}")
    expect(content).to include("name: String@c")
    expect(content).to include("callback: FN(TargetInt) -> TargetInt CALLCONV C")
    expect(content.lines.map { |line| line.chomp.length }.max).to be <= 120
    expect(Formatter.format(content)).to eq(content)
  end

  it "writes atomically, detects unchanged output, and protects edited bindings" do
    content = described_class.generate(header: @header, output: @output, library: "fixture")

    expect(described_class.write(output: @output, content: content, force: false)).to eq(:written)
    expect(described_class.current?(output: @output, content: content)).to be(true)
    expect(described_class.write(output: @output, content: content, force: false)).to eq(:unchanged)

    File.write(@output, "# locally edited\n")
    expect(described_class.current?(output: @output, content: content)).to be(false)
    expect { described_class.write(output: @output, content: content, force: false) }
      .to raise_error(CFFIGenerator::Error, /Refusing to overwrite/)
    expect(described_class.write(output: @output, content: content, force: true)).to eq(:written)
    expect(File.read(@output)).to eq(content)
  end

  it "runs the real c-ffi CLI and supports stale-binding checks" do
    clear = File.expand_path("../../clear", __dir__)
    out, err, status = Open3.capture3(clear, "c-ffi", @header, @output, "--link", "fixture")
    expect(status).to be_success, err
    expect(out).to include(@output)

    _, fmt_err, fmt_status = Open3.capture3(clear, "fmt", "--check", "--no-warn", @output)
    expect(fmt_status).to be_success, fmt_err

    check_out, check_err, check_status = Open3.capture3(
      clear, "c-ffi", @header, @output, "--link=fixture", "--check"
    )
    expect(check_status).to be_success, check_err
    expect(check_out).to include("up to date")

    File.open(@output, "a") { |file| file << "# stale\n" }
    _, stale_err, stale_status = Open3.capture3(
      clear, "c-ffi", @header, @output, "--link", "fixture", "--check"
    )
    expect(stale_status).not_to be_success
    expect(stale_err).to include("stale or missing")

    _, protected_err, protected_status = Open3.capture3(
      clear, "c-ffi", @header, @output, "--link", "fixture"
    )
    expect(protected_status).not_to be_success
    expect(protected_err).to include("Refusing to overwrite")

    _, force_err, force_status = Open3.capture3(
      clear, "c-ffi", @header, @output, "--link", "fixture", "--force"
    )
    expect(force_status).to be_success, force_err
  end

  it "requires a real header, output directory, and library" do
    expect do
      described_class.generate(header: "missing.h", output: @output, library: "fixture")
    end.to raise_error(CFFIGenerator::Error, /header not found/)

    missing_output = File.join(@directory, "missing", "fixture.ffi.clear")
    expect do
      described_class.generate(header: @header, output: missing_output, library: "fixture")
    end.to raise_error(CFFIGenerator::Error, /Output directory does not exist/)

    expect do
      described_class.generate(header: @header, output: @output, library: "")
    end.to raise_error(CFFIGenerator::Error, /library name cannot be empty/)
  end
end
