ignore:
  - "tools/"
  - "zig/*-test.zig"
  - "zig/**/*-test.zig"
  - "zig/vopr-*.zig"
  - "zig/**/vopr-*.zig"
  - "zig/loom-*.zig"
  - "zig/**/loom-*.zig"
  - "zig/*-vopr.zig"
  - "zig/**/*-vopr.zig"
  - "zig/*-loom.zig"
  - "zig/**/*-loom.zig"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  ruby:
    paths:
      - src/
      - spec/
      - gems/
    carryforward: false
    joined: false
  zig:
    paths:
      - zig/
    carryforward: false
    joined: false
  nil-kill:
    paths:
      - gems/nil-kill/
    carryforward: false
    joined: false
