ignore:
  - "tools/"
  - "zig/all-tests.zig"
  - "zig/all-fuzz.zig"
  - "zig/._clear_cov_*.zig"
  - "all-tests.zig"
  - "all-fuzz.zig"
  - "._clear_cov_*.zig"
  - "*-test.zig"
  - "**/*-test.zig"
  - "vopr-*.zig"
  - "**/vopr-*.zig"
  - "loom-*.zig"
  - "**/loom-*.zig"
  - "*-vopr.zig"
  - "**/*-vopr.zig"
  - "*-loom.zig"
  - "**/*-loom.zig"
  - "zig/*-test.zig"
  - "zig/**/*-test.zig"
  - "zig/vopr-*.zig"
  - "zig/**/vopr-*.zig"
  - "zig/loom-*.zig"
  - "zig/**/loom-*.zig"
  - "zig/*-vopr.zig"
  - "zig/**/*-vopr.zig"
  - "zig/*-loom.zig"
  - "zig/**/*-loom.zig"

fixes:
  - "runtime/::zig/runtime/"
  - "lib/::zig/lib/"
  - "experimental/::zig/experimental/"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  ruby:
    paths:
      - compiler/
    carryforward: false
    joined: false
  zig:
    paths:
      - zig/
    carryforward: false
    joined: false
  lineage-rust:
    paths:
      - gems/lineage/
    carryforward: false
    joined: false
  go:
    paths:
      - gems/boobytrap/
    carryforward: false
    joined: false
  gems:
    paths:
      - gems/
    carryforward: false
    joined: false
  nil-kill-rust:
    paths:
      - gems/nil-kill/
    carryforward: false
    joined: false
  zig-mutants:
    paths:
      - gems/zig-mutants/
    carryforward: false
    joined: false
