
// Verdicts taken from nil-kill's Ruby implementation over every Sorbet
// signature in this workspace. The port has to agree with the code it
// replaces on real input, not just on cases chosen to illustrate the rules.
use super::*;

    #[test]
    fn every_corpus_type_gets_the_same_verdict_as_ruby() {
        let cases: &[(&str, bool)] = &[
            ("CapturedOutput", true),
            ("CohortContribution", true),
            ("CommandLimits", true),
            ("CommandResult", true),
            ("CommandRunner", true),
            ("ContributionAnalysis", true),
            ("Corpus", true),
            ("CounterfactualProvenance", true),
            ("CounterfactualRequest", true),
            ("CounterfactualResult", true),
            ("Coverage", true),
            ("EvidenceCompleteness", true),
            ("EvidenceGate", true),
            ("EvidenceReport", true),
            ("EvidenceScope", true),
            ("FieldTypes", true),
            ("FindingKind", true),
            ("Float", true),
            ("IO", true),
            ("Integer", true),
            ("MatrixCheck", true),
            ("OracleExecutionRequest", true),
            ("OracleExecutionResult", true),
            ("OracleFact", true),
            ("OracleFacts", true),
            ("OracleMutationKind", true),
            ("OracleMutationPlan", true),
            ("OracleRewriteAdapter", true),
            ("OracleSensitivity", true),
            ("OracleSensitivityAnalysis", true),
            ("Regexp", true),
            ("ReviewFindingKind", true),
            ("SourceSpan", true),
            ("StabilityAnalysis", true),
            ("String", true),
            ("SubsumptionAnalysis", true),
            ("T.nilable(CohortEvidenceVector)", true),
            ("T.nilable(CommandResult)", true),
            ("T.nilable(ContributionAnalysis)", true),
            ("T.nilable(CounterfactualProvenance)", true),
            ("T.nilable(CounterfactualResult)", true),
            ("T.nilable(EvidenceScope)", true),
            ("T.nilable(IO)", true),
            ("T.nilable(Integer)", true),
            ("T.nilable(OracleKind)", true),
            ("T.nilable(OracleMutationPlan)", true),
            ("T.nilable(OracleRewrite)", true),
            ("T.nilable(OracleSensitivityAnalysis)", true),
            ("T.nilable(Process::Status)", true),
            ("T.nilable(SourceSpan)", true),
            ("T.nilable(StabilityAnalysis)", true),
            ("T.nilable(String)", true),
            ("T.nilable(T::Array[Integer])", true),
            ("T.nilable(T::Array[String])", true),
            ("T.nilable(T::Boolean)", true),
            ("T.nilable(Thread)", true),
            ("T.nilable([Integer, Integer])", true),
            ("T.proc.params(archived_source_path: String, resolved_revision: String).returns(T.untyped)", false),
            ("T.proc.params(node: T.untyped).void", false),
            ("T.untyped", false),
            ("T::Array[EquivalentMutantGroup]", true),
            ("T::Array[EvidenceVector]", true),
            ("T::Array[FindingKind]", true),
            ("T::Array[FrontierRanking]", true),
            ("T::Array[IndexedKillSet]", true),
            ("T::Array[Integer]", true),
            ("T::Array[KillTrial]", true),
            ("T::Array[OracleFact]", true),
            ("T::Array[OracleMutationPlan]", true),
            ("T::Array[OracleRewrite]", true),
            ("T::Array[OracleTrial]", true),
            ("T::Array[RerunCandidate]", true),
            ("T::Array[ReviewFinding]", true),
            ("T::Array[String]", true),
            ("T::Array[SubsumptionRelation]", true),
            ("T::Array[T.untyped]", false),
            ("T::Array[T::Hash[String, String]]", true),
            ("T::Array[T::Hash[String, T.untyped]]", false),
            ("T::Array[TestContribution]", true),
            ("T::Boolean", true),
            ("T::Hash[String, Float]", true),
            ("T::Hash[String, Integer]", true),
            ("T::Hash[String, String]", true),
            ("T::Hash[String, T.untyped]", false),
            ("T::Hash[String, T::Array[String]]", true),
            ("T::Hash[String, T::Array[T::Boolean]]", true),
            ("T::Hash[String, T::Set[String]]", true),
            ("T::Hash[[String, String], T::Array[T::Boolean]]", true),
            ("T::Set[String]", true),
            ("TYPE", true),
            ("TestContribution", true),
            ("TestObservation", true),
            ("TestOutcome", true),
            ("TestResultParser", true),
            ("Thread", true),
            ("[String, OracleRewrite]", true),
            ("[String, String]", true),
            ("[T::Boolean, T.nilable(String)]", true),
            ("[T::Hash[[String, String], T::Array[T::Boolean]], T::Boolean]", true),
        ];
        let mut disagreed = Vec::new();
        for (type_text, expected) in cases {
            if strong_trace_type(type_text) != *expected {
                disagreed.push(*type_text);
            }
        }
        assert!(disagreed.is_empty(), "disagreed with Ruby on: {disagreed:?}");
    }

    #[test]
    fn every_corpus_signature_parses_to_the_same_parameters_as_ruby() {
        let cases: &[(&str, &[(&str, &str)], &str)] = &[
            ("sig do\n          params(\n            fact: OracleFact,\n            original: T::Array[String],\n            trials: T::Array[OracleTrial],\n            rewrite: T.nilable(OracleRewrite),\n            original_known: T::Boolean,\n            expected_trial_ids: T::Array[String],\n            min_trials: Integer,\n            control_verified: T::Boolean,\n            control_reason: T.nilable(String),\n          ).returns(OracleSensitivity)\n        end", &[("fact", "OracleFact"), ("original", "T::Array[String]"), ("trials", "T::Array[OracleTrial]"), ("rewrite", "T.nilable(OracleRewrite)"), ("original_known", "T::Boolean"), ("expected_trial_ids", "T::Array[String]"), ("min_trials", "Integer"), ("control_verified", "T::Boolean"), ("control_reason", "T.nilable(String)")], "OracleSensitivity"),
            ("sig do\n          params(original: T::Array[String], trials: T::Array[OracleTrial], expected_trial_ids: T::Array[String], min_trials: Integer).returns(T.nilable(String))\n        end", &[("original", "T::Array[String]"), ("trials", "T::Array[OracleTrial]"), ("expected_trial_ids", "T::Array[String]"), ("min_trials", "Integer")], "T.nilable(String)"),
            ("sig do\n        abstract.params(\n          command: T::Array[String],\n          chdir: String,\n          limits: CommandLimits,\n        ).returns(CommandResult)\n      end", &[("command", "T::Array[String]"), ("chdir", "String"), ("limits", "CommandLimits")], "CommandResult"),
            ("sig do\n        abstract.params(fact: OracleFact, plan: OracleMutationPlan, source: String, language: String).returns([String, OracleRewrite])\n      end", &[("fact", "OracleFact"), ("plan", "OracleMutationPlan"), ("source", "String"), ("language", "String")], "[String, OracleRewrite]"),
            ("sig do\n        abstract.params(test_id: String, source_path: String, language: String).returns(T::Array[OracleFact])\n      end", &[("test_id", "String"), ("source_path", "String"), ("language", "String")], "T::Array[OracleFact]"),
            ("sig do\n        override.params(\n          command: T::Array[String],\n          chdir: String,\n          limits: CommandLimits,\n        ).returns(CommandResult)\n      end", &[("command", "T::Array[String]"), ("chdir", "String"), ("limits", "CommandLimits")], "CommandResult"),
            ("sig do\n        override.params(fact: OracleFact, plan: OracleMutationPlan, source: String, language: String).returns([String, OracleRewrite])\n      end", &[("fact", "OracleFact"), ("plan", "OracleMutationPlan"), ("source", "String"), ("language", "String")], "[String, OracleRewrite]"),
            ("sig do\n        override.params(test_id: String, source_path: String, language: String).returns(T::Array[OracleFact])\n      end", &[("test_id", "String"), ("source_path", "String"), ("language", "String")], "T::Array[OracleFact]"),
            ("sig do\n        params(\n          contribution: TestContribution,\n          all_contributions: T::Array[TestContribution],\n          covered_sets: T::Hash[String, T::Set[String]],\n          killed_sets: T::Hash[String, T::Set[String]],\n        ).returns(T::Array[String])\n      end", &[("contribution", "TestContribution"), ("all_contributions", "T::Array[TestContribution]"), ("covered_sets", "T::Hash[String, T::Set[String]]"), ("killed_sets", "T::Hash[String, T::Set[String]]")], "T::Array[String]"),
            ("sig do\n        params(\n          contributions: ContributionAnalysis,\n          subsumption: SubsumptionAnalysis,\n          counterfactual_test_ids: T::Array[String],\n        ).returns(T.nilable(CohortEvidenceVector))\n      end", &[("contributions", "ContributionAnalysis"), ("subsumption", "SubsumptionAnalysis"), ("counterfactual_test_ids", "T::Array[String]")], "T.nilable(CohortEvidenceVector)"),
            ("sig do\n        params(\n          contributions: ContributionAnalysis,\n          subsumption: SubsumptionAnalysis,\n          stability: T.nilable(StabilityAnalysis),\n          counterfactual: T.nilable(CounterfactualResult),\n          oracle_sensitivity: T.nilable(OracleSensitivityAnalysis),\n          counterfactual_test_ids: T::Array[String],\n          cohort: T.nilable(CohortEvidenceVector),\n          vectors: T::Array[EvidenceVector],\n          high_cost_ms: Float,\n          gate: EvidenceGate,\n        ).returns(T::Array[ReviewFinding])\n      end", &[("contributions", "ContributionAnalysis"), ("subsumption", "SubsumptionAnalysis"), ("stability", "T.nilable(StabilityAnalysis)"), ("counterfactual", "T.nilable(CounterfactualResult)"), ("oracle_sensitivity", "T.nilable(OracleSensitivityAnalysis)"), ("counterfactual_test_ids", "T::Array[String]"), ("cohort", "T.nilable(CohortEvidenceVector)"), ("vectors", "T::Array[EvidenceVector]"), ("high_cost_ms", "Float"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig do\n        params(\n          contributions: ContributionAnalysis,\n          subsumption: SubsumptionAnalysis,\n          stability: T.nilable(StabilityAnalysis),\n          counterfactual: T.nilable(CounterfactualResult),\n          oracle_sensitivity: T.nilable(OracleSensitivityAnalysis),\n          counterfactual_test_ids: T::Array[String],\n          runtimes: T::Hash[String, Float],\n          cohort: T.nilable(CohortEvidenceVector),\n          gate: EvidenceGate,\n        ).returns(T::Array[EvidenceVector])\n      end", &[("contributions", "ContributionAnalysis"), ("subsumption", "SubsumptionAnalysis"), ("stability", "T.nilable(StabilityAnalysis)"), ("counterfactual", "T.nilable(CounterfactualResult)"), ("oracle_sensitivity", "T.nilable(OracleSensitivityAnalysis)"), ("counterfactual_test_ids", "T::Array[String]"), ("runtimes", "T::Hash[String, Float]"), ("cohort", "T.nilable(CohortEvidenceVector)"), ("gate", "EvidenceGate")], "T::Array[EvidenceVector]"),
            ("sig do\n        params(\n          contributions: ContributionAnalysis,\n          subsumption: SubsumptionAnalysis,\n          stability: T.nilable(StabilityAnalysis),\n          counterfactual: T.nilable(CounterfactualResult),\n          oracle_sensitivity: T.nilable(OracleSensitivityAnalysis),\n          counterfactual_test_ids: T::Array[String],\n          runtimes: T::Hash[String, Float],\n          high_cost_ms: Float,\n          cost_comparable: T::Boolean,\n        ).returns(EvidenceReport)\n      end", &[("contributions", "ContributionAnalysis"), ("subsumption", "SubsumptionAnalysis"), ("stability", "T.nilable(StabilityAnalysis)"), ("counterfactual", "T.nilable(CounterfactualResult)"), ("oracle_sensitivity", "T.nilable(OracleSensitivityAnalysis)"), ("counterfactual_test_ids", "T::Array[String]"), ("runtimes", "T::Hash[String, Float]"), ("high_cost_ms", "Float"), ("cost_comparable", "T::Boolean")], "EvidenceReport"),
            ("sig do\n        params(\n          contributions: ContributionAnalysis,\n          subsumption: SubsumptionAnalysis,\n          stability: T.nilable(StabilityAnalysis),\n          counterfactual: T.nilable(CounterfactualResult),\n          oracle_sensitivity: T.nilable(OracleSensitivityAnalysis),\n        ).void\n      end", &[("contributions", "ContributionAnalysis"), ("subsumption", "SubsumptionAnalysis"), ("stability", "T.nilable(StabilityAnalysis)"), ("counterfactual", "T.nilable(CounterfactualResult)"), ("oracle_sensitivity", "T.nilable(OracleSensitivityAnalysis)")], ""),
            ("sig do\n        params(\n          corpus: Corpus,\n          scope: T.nilable(EvidenceScope),\n          revision: String,\n          repository: T.nilable(String),\n          max_distinct_kill_sets: Integer,\n          max_relation_checks: Integer,\n        ).void\n      end", &[("corpus", "Corpus"), ("scope", "T.nilable(EvidenceScope)"), ("revision", "String"), ("repository", "T.nilable(String)"), ("max_distinct_kill_sets", "Integer"), ("max_relation_checks", "Integer")], ""),
            ("sig do\n        params(\n          counterfactual: T.nilable(CounterfactualResult),\n          test_ids: T::Array[String],\n          cohort: T.nilable(CohortEvidenceVector),\n          gate: EvidenceGate,\n        ).returns(T::Array[ReviewFinding])\n      end", &[("counterfactual", "T.nilable(CounterfactualResult)"), ("test_ids", "T::Array[String]"), ("cohort", "T.nilable(CohortEvidenceVector)"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig do\n        params(\n          counterfactual: T.nilable(CounterfactualResult),\n          test_ids: T::Array[String],\n          test_id: String,\n          cohort: T.nilable(CohortEvidenceVector),\n        ).returns(T.nilable(T::Boolean))\n      end", &[("counterfactual", "T.nilable(CounterfactualResult)"), ("test_ids", "T::Array[String]"), ("test_id", "String"), ("cohort", "T.nilable(CohortEvidenceVector)")], "T.nilable(T::Boolean)"),
            ("sig do\n        params(\n          facts: OracleFacts,\n          original_kills: T::Hash[String, T::Array[String]],\n          disabled_trials: T::Array[OracleTrial],\n          rewrites: T::Array[OracleRewrite],\n          scope: T.nilable(EvidenceScope),\n          trial_ids: T.nilable(T::Array[String]),\n          min_trials: Integer,\n          execution_results: T::Array[T::Hash[String, T.untyped]],\n        ).returns(OracleSensitivityAnalysis)\n      end", &[("facts", "OracleFacts"), ("original_kills", "T::Hash[String, T::Array[String]]"), ("disabled_trials", "T::Array[OracleTrial]"), ("rewrites", "T::Array[OracleRewrite]"), ("scope", "T.nilable(EvidenceScope)"), ("trial_ids", "T.nilable(T::Array[String])"), ("min_trials", "Integer"), ("execution_results", "T::Array[T::Hash[String, T.untyped]]")], "OracleSensitivityAnalysis"),
            ("sig do\n        params(\n          frontier: T::Array[String],\n          contributions: T.nilable(ContributionAnalysis),\n        ).returns(T::Array[FrontierRanking])\n      end", &[("frontier", "T::Array[String]"), ("contributions", "T.nilable(ContributionAnalysis)")], "T::Array[FrontierRanking]"),
            ("sig do\n        params(\n          frontier: T::Array[String],\n          contributions: T.nilable(ContributionAnalysis),\n        ).returns(T::Array[String])\n      end", &[("frontier", "T::Array[String]"), ("contributions", "T.nilable(ContributionAnalysis)")], "T::Array[String]"),
            ("sig do\n        params(\n          head: CommandResult,\n          reason: String,\n          repository_status: CommandResult,\n          revision_resolution: CommandResult,\n          baseline_head: T.nilable(CommandResult),\n          worktree: T.nilable(CommandResult),\n          reverse_patch: T.nilable(CommandResult),\n          build: T.nilable(CommandResult),\n          new_tests: T.nilable(CommandResult),\n          baseline_tests: T.nilable(CommandResult),\n          scope: T.nilable(EvidenceScope),\n          provenance: T.nilable(CounterfactualProvenance),\n        ).returns(CounterfactualResult)\n      end", &[("head", "CommandResult"), ("reason", "String"), ("repository_status", "CommandResult"), ("revision_resolution", "CommandResult"), ("baseline_head", "T.nilable(CommandResult)"), ("worktree", "T.nilable(CommandResult)"), ("reverse_patch", "T.nilable(CommandResult)"), ("build", "T.nilable(CommandResult)"), ("new_tests", "T.nilable(CommandResult)"), ("baseline_tests", "T.nilable(CommandResult)"), ("scope", "T.nilable(EvidenceScope)"), ("provenance", "T.nilable(CounterfactualProvenance)")], "CounterfactualResult"),
            ("sig do\n        params(\n          kill_sets: T::Array[IndexedKillSet],\n          relations: T::Array[SubsumptionRelation],\n        ).returns(T::Array[String])\n      end", &[("kill_sets", "T::Array[IndexedKillSet]"), ("relations", "T::Array[SubsumptionRelation]")], "T::Array[String]"),
            ("sig do\n        params(\n          new_test_ids: T::Array[String],\n          baseline_test_ids: T::Array[String],\n        ).returns(ContributionAnalysis)\n      end", &[("new_test_ids", "T::Array[String]"), ("baseline_test_ids", "T::Array[String]")], "ContributionAnalysis"),
            ("sig do\n        params(\n          patch_path: String,\n          patch_sha256: T.nilable(String),\n          resolved_revision: T.nilable(String),\n          clean_worktree: T::Boolean,\n          worktree_path: T.nilable(String),\n        ).returns(CounterfactualProvenance)\n      end", &[("patch_path", "String"), ("patch_sha256", "T.nilable(String)"), ("resolved_revision", "T.nilable(String)"), ("clean_worktree", "T::Boolean"), ("worktree_path", "T.nilable(String)")], "CounterfactualProvenance"),
            ("sig do\n        params(\n          repository: String,\n          revision: String,\n          source_path: String,\n          block: T.proc.params(archived_source_path: String, resolved_revision: String).returns(T.untyped),\n        ).returns(T.untyped)\n      end", &[("repository", "String"), ("revision", "String"), ("source_path", "String"), ("block", "T.proc.params(archived_source_path: String, resolved_revision: String).returns(T.untyped)")], "T.untyped"),
            ("sig do\n        params(\n          revision: String,\n          selection_scope: String,\n          mutants: T::Array[T::Hash[String, T.untyped]],\n          test_ids: T::Array[String],\n          repository: T.nilable(String),\n        ).returns(EvidenceScope)\n      end", &[("revision", "String"), ("selection_scope", "String"), ("mutants", "T::Array[T::Hash[String, T.untyped]]"), ("test_ids", "T::Array[String]"), ("repository", "T.nilable(String)")], "EvidenceScope"),
            ("sig do\n        params(\n          test_id: String,\n          observations: T::Hash[[String, String], T::Array[T::Boolean]],\n        ).returns(T::Array[String])\n      end", &[("test_id", "String"), ("observations", "T::Hash[[String, String], T::Array[T::Boolean]]")], "T::Array[String]"),
            ("sig do\n        params(\n          test_id: String,\n          observations: T::Hash[[String, String], T::Array[T::Boolean]],\n        ).returns(T::Hash[String, T::Array[T::Boolean]])\n      end", &[("test_id", "String"), ("observations", "T::Hash[[String, String], T::Array[T::Boolean]]")], "T::Hash[String, T::Array[T::Boolean]]"),
            ("sig do\n        params(\n          test_ids: T::Array[String],\n          mutant_ids: T::Array[String],\n          trial_ids: T::Array[Integer],\n          observations: T::Hash[[String, String], T::Array[T::Boolean]],\n          duplicate_observations: T::Boolean,\n        ).returns(MatrixCheck)\n      end", &[("test_ids", "T::Array[String]"), ("mutant_ids", "T::Array[String]"), ("trial_ids", "T::Array[Integer]"), ("observations", "T::Hash[[String, String], T::Array[T::Boolean]]"), ("duplicate_observations", "T::Boolean")], "MatrixCheck"),
            ("sig do\n        params(\n          trials: T::Array[KillTrial],\n          test_ids: T.nilable(T::Array[String]),\n          mutant_ids: T.nilable(T::Array[String]),\n          trial_ids: T.nilable(T::Array[Integer]),\n        ).returns(StabilityAnalysis)\n      end", &[("trials", "T::Array[KillTrial]"), ("test_ids", "T.nilable(T::Array[String])"), ("mutant_ids", "T.nilable(T::Array[String])"), ("trial_ids", "T.nilable(T::Array[Integer])")], "StabilityAnalysis"),
            ("sig do\n        params(\n          trials: T::Array[KillTrial],\n          test_ids: T::Array[String],\n          mutant_ids: T::Array[String],\n          trial_ids: T::Array[Integer],\n        ).returns([T::Hash[[String, String], T::Array[T::Boolean]], T::Boolean])\n      end", &[("trials", "T::Array[KillTrial]"), ("test_ids", "T::Array[String]"), ("mutant_ids", "T::Array[String]"), ("trial_ids", "T::Array[Integer]")], "[T::Hash[[String, String], T::Array[T::Boolean]], T::Boolean]"),
            ("sig do\n        params(\n          vectors: T::Array[EvidenceVector],\n          threshold: Float,\n          gate: EvidenceGate,\n        ).returns(T::Array[ReviewFinding])\n      end", &[("vectors", "T::Array[EvidenceVector]"), ("threshold", "Float"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig do\n        params(revision: String, selection_scope: String, repository: T.nilable(String)).returns(EvidenceScope)\n      end", &[("revision", "String"), ("selection_scope", "String"), ("repository", "T.nilable(String)")], "EvidenceScope"),
            ("sig do\n        params(stability: T.nilable(StabilityAnalysis), gate: EvidenceGate).returns(T::Array[ReviewFinding])\n      end", &[("stability", "T.nilable(StabilityAnalysis)"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig do\")\n        end", &[], ""),
            ("sig { ... .void }", &[], ""),
            ("sig { abstract.params(result: CommandResult).returns(TestOutcome) }", &[("result", "CommandResult")], "TestOutcome"),
            ("sig { override.params(result: CommandResult).returns(TestOutcome) }", &[("result", "CommandResult")], "TestOutcome"),
            ("sig { params(analysis: ContributionAnalysis).returns(T::Array[RerunCandidate]) }", &[("analysis", "ContributionAnalysis")], "T::Array[RerunCandidate]"),
            ("sig { params(artifact: OracleFacts).void }", &[("artifact", "OracleFacts")], ""),
            ("sig { params(binary: String, runner: T.untyped, framework: T.nilable(String), source_identity: T.nilable(String)).void }", &[("binary", "String"), ("runner", "T.untyped"), ("framework", "T.nilable(String)"), ("source_identity", "T.nilable(String)")], ""),
            ("sig { params(call: T.untyped, calls: T::Array[T.untyped], framework: String).returns(SourceSpan) }", &[("call", "T.untyped"), ("calls", "T::Array[T.untyped]"), ("framework", "String")], "SourceSpan"),
            ("sig { params(call: T.untyped, test_id: String, source: String, framework: String).returns(T::Boolean) }", &[("call", "T.untyped"), ("test_id", "String"), ("source", "String"), ("framework", "String")], "T::Boolean"),
            ("sig { params(command: T::Array[String], chdir: String).returns(CommandResult) }", &[("command", "T::Array[String]"), ("chdir", "String")], "CommandResult"),
            ("sig { params(command_runner: CommandRunner, adapter: OracleRewriteAdapter, parser: TestResultParser).void }", &[("command_runner", "CommandRunner"), ("adapter", "OracleRewriteAdapter"), ("parser", "TestResultParser")], ""),
            ("sig { params(complete: T.nilable(T::Boolean)).returns(T.nilable(String)) }", &[("complete", "T.nilable(T::Boolean)")], "T.nilable(String)"),
            ("sig { params(contribution: TestContribution, gate: EvidenceGate).returns(T::Array[ReviewFinding]) }", &[("contribution", "TestContribution"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig { params(contributions: ContributionAnalysis, cohort_vector: T.nilable(CohortEvidenceVector), gate: EvidenceGate).returns(T::Array[ReviewFinding]) }", &[("contributions", "ContributionAnalysis"), ("cohort_vector", "T.nilable(CohortEvidenceVector)"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig { params(contributions: ContributionAnalysis, cost_comparable: T::Boolean).returns(EvidenceGate) }", &[("contributions", "ContributionAnalysis"), ("cost_comparable", "T::Boolean")], "EvidenceGate"),
            ("sig { params(contributions: ContributionAnalysis, gate: EvidenceGate).returns(T::Array[ReviewFinding]) }", &[("contributions", "ContributionAnalysis"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig { params(contributions: T.nilable(ContributionAnalysis)).returns(SubsumptionAnalysis) }", &[("contributions", "T.nilable(ContributionAnalysis)")], "SubsumptionAnalysis"),
            ("sig { params(contributions: T.nilable(ContributionAnalysis), reason: String).returns(SubsumptionAnalysis) }", &[("contributions", "T.nilable(ContributionAnalysis)"), ("reason", "String")], "SubsumptionAnalysis"),
            ("sig { params(corpus: Corpus, scope: T.nilable(EvidenceScope), revision: String, repository: T.nilable(String)).void }", &[("corpus", "Corpus"), ("scope", "T.nilable(EvidenceScope)"), ("revision", "String"), ("repository", "T.nilable(String)")], ""),
            ("sig { params(corpus: Corpus, threshold: Integer, scope: T.nilable(EvidenceScope), revision: String, repository: T.nilable(String)).void }", &[("corpus", "Corpus"), ("threshold", "Integer"), ("scope", "T.nilable(EvidenceScope)"), ("revision", "String"), ("repository", "T.nilable(String)")], ""),
            ("sig { params(counterfactual: T.nilable(CounterfactualResult)).returns(T::Boolean) }", &[("counterfactual", "T.nilable(CounterfactualResult)")], "T::Boolean"),
            ("sig { params(fact: OracleFact).returns(T.nilable(OracleMutationPlan)) }", &[("fact", "OracleFact")], "T.nilable(OracleMutationPlan)"),
            ("sig { params(fact: OracleFact).returns(T::Array[OracleMutationPlan]) }", &[("fact", "OracleFact")], "T::Array[OracleMutationPlan]"),
            ("sig { params(facts: OracleFacts, scope: T.nilable(EvidenceScope)).void }", &[("facts", "OracleFacts"), ("scope", "T.nilable(EvidenceScope)")], ""),
            ("sig { params(finding: FindingKind).returns(T::Boolean) }", &[("finding", "FindingKind")], "T::Boolean"),
            ("sig { params(framework: String, call: T.untyped).returns(T.nilable(OracleKind)) }", &[("framework", "String"), ("call", "T.untyped")], "T.nilable(OracleKind)"),
            ("sig { params(framework: String, call: T.untyped).returns(T::Boolean) }", &[("framework", "String"), ("call", "T.untyped")], "T::Boolean"),
            ("sig { params(grammar_paths: T::Hash[String, String], framework: T.nilable(String), tree_sitter: T.untyped, source_identity: T.nilable(String)).void }", &[("grammar_paths", "T::Hash[String, String]"), ("framework", "T.nilable(String)"), ("tree_sitter", "T.untyped"), ("source_identity", "T.nilable(String)")], ""),
            ("sig { params(input_completeness: String, blocker_kinds: T::Array[String]).returns(Coverage) }", &[("input_completeness", "String"), ("blocker_kinds", "T::Array[String]")], "Coverage"),
            ("sig { params(input_completeness: T.nilable(String), blocker_kinds: T::Array[String]).returns(Coverage) }", &[("input_completeness", "T.nilable(String)"), ("blocker_kinds", "T::Array[String]")], "Coverage"),
            ("sig { params(io: IO, limit: Integer).returns(CapturedOutput) }", &[("io", "IO"), ("limit", "Integer")], "CapturedOutput"),
            ("sig { params(io: T.nilable(IO)).void }", &[("io", "T.nilable(IO)")], ""),
            ("sig { params(kill_sets: T::Array[IndexedKillSet]).returns(T::Array[EquivalentMutantGroup]) }", &[("kill_sets", "T::Array[IndexedKillSet]")], "T::Array[EquivalentMutantGroup]"),
            ("sig { params(kill_sets: T::Array[IndexedKillSet]).returns(T::Array[SubsumptionRelation]) }", &[("kill_sets", "T::Array[IndexedKillSet]")], "T::Array[SubsumptionRelation]"),
            ("sig { params(kind: ReviewFindingKind).returns(String) }", &[("kind", "ReviewFindingKind")], "String"),
            ("sig { params(left: Integer, right: Integer).returns(T::Boolean) }", &[("left", "Integer"), ("right", "Integer")], "T::Boolean"),
            ("sig { params(left: T::Set[String], right: T::Set[String]).returns(T::Boolean) }", &[("left", "T::Set[String]"), ("right", "T::Set[String]")], "T::Boolean"),
            ("sig { params(line: String, column: Integer).returns(T.nilable(Integer)) }", &[("line", "String"), ("column", "Integer")], "T.nilable(Integer)"),
            ("sig { params(mutation: OracleMutationKind, original: String, language: String, framework: String).returns(String) }", &[("mutation", "OracleMutationKind"), ("original", "String"), ("language", "String"), ("framework", "String")], "String"),
            ("sig { params(new_test_ids: T::Array[String], baseline_test_ids: T::Array[String]).returns(CohortContribution) }", &[("new_test_ids", "T::Array[String]"), ("baseline_test_ids", "T::Array[String]")], "CohortContribution"),
            ("sig { params(new_test_ids: T::Array[String], baseline_test_ids: T::Array[String]).void }", &[("new_test_ids", "T::Array[String]"), ("baseline_test_ids", "T::Array[String]")], ""),
            ("sig { params(node: T.untyped).returns(SourceSpan) }", &[("node", "T.untyped")], "SourceSpan"),
            ("sig { params(node: T.untyped, block: T.proc.params(node: T.untyped).void).void }", &[("node", "T.untyped"), ("block", "T.proc.params(node: T.untyped).void")], ""),
            ("sig { params(node: T.untyped, framework: String).returns(T.untyped) }", &[("node", "T.untyped"), ("framework", "String")], "T.untyped"),
            ("sig { params(node: T.untyped, framework: String).returns(T::Boolean) }", &[("node", "T.untyped"), ("framework", "String")], "T::Boolean"),
            ("sig { params(oracle: T.nilable(OracleSensitivityAnalysis), gate: EvidenceGate).returns(T::Array[ReviewFinding]) }", &[("oracle", "T.nilable(OracleSensitivityAnalysis)"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig { params(original: String, language: String, framework: String).returns(String) }", &[("original", "String"), ("language", "String"), ("framework", "String")], "String"),
            ("sig { params(original: String, method: String).returns(T::Array[String]) }", &[("original", "String"), ("method", "String")], "T::Array[String]"),
            ("sig { params(original: String, method: String, actual_index: Integer, language: String).returns(String) }", &[("original", "String"), ("method", "String"), ("actual_index", "Integer"), ("language", "String")], "String"),
            ("sig { params(original: String, method: String, matcher_pattern: Regexp, language: String).returns(String) }", &[("original", "String"), ("method", "String"), ("matcher_pattern", "Regexp"), ("language", "String")], "String"),
            ("sig { params(original: T::Array[String], trials: T::Array[OracleTrial], expected_trial_ids: T::Array[String]).returns(T::Boolean) }", &[("original", "T::Array[String]"), ("trials", "T::Array[OracleTrial]"), ("expected_trial_ids", "T::Array[String]")], "T::Boolean"),
            ("sig { params(other: T.nilable(EvidenceScope)).returns(T::Boolean) }", &[("other", "T.nilable(EvidenceScope)")], "T::Boolean"),
            ("sig { params(path: String).returns(OracleFacts) }", &[("path", "String")], "OracleFacts"),
            ("sig { params(path: String).returns(String) }", &[("path", "String")], "String"),
            ("sig { params(path: String).returns(T.nilable(String)) }", &[("path", "String")], "T.nilable(String)"),
            ("sig { params(path: String).void }", &[("path", "String")], ""),
            ("sig { params(raw: T.untyped).returns(SourceSpan) }", &[("raw", "T.untyped")], "SourceSpan"),
            ("sig { params(reason: String).returns(CommandResult) }", &[("reason", "String")], "CommandResult"),
            ("sig { params(report: T.untyped).returns(Corpus) }", &[("report", "T.untyped")], "Corpus"),
            ("sig { params(repository: String, revision: String).returns(String) }", &[("repository", "String"), ("revision", "String")], "String"),
            ("sig { params(request: CounterfactualRequest, runner: CommandRunner).void }", &[("request", "CounterfactualRequest"), ("runner", "CommandRunner")], ""),
            ("sig { params(request: OracleExecutionRequest).returns(OracleExecutionResult) }", &[("request", "OracleExecutionRequest")], "OracleExecutionResult"),
            ("sig { params(request: OracleExecutionRequest).void }", &[("request", "OracleExecutionRequest")], ""),
            ("sig { params(request: OracleExecutionRequest, directory: String).returns(String) }", &[("request", "OracleExecutionRequest"), ("directory", "String")], "String"),
            ("sig { params(result: CommandResult).returns(TestOutcome) }", &[("result", "CommandResult")], "TestOutcome"),
            ("sig { params(result: OracleSensitivity).returns(T::Boolean) }", &[("result", "OracleSensitivity")], "T::Boolean"),
            ("sig { params(revision: String, repository: T.nilable(String)).returns(String) }", &[("revision", "String"), ("repository", "T.nilable(String)")], "String"),
            ("sig { params(rewrite: T.nilable(OracleRewrite)).returns(T.nilable(String)) }", &[("rewrite", "T.nilable(OracleRewrite)")], "T.nilable(String)"),
            ("sig { params(root: String).returns(FieldTypes) }", &[("root", "String")], "FieldTypes"),
            ("sig { params(root: String, path: String).returns(String) }", &[("root", "String"), ("path", "String")], "String"),
            ("sig { params(row: T.untyped).returns(OracleFact) }", &[("row", "T.untyped")], "OracleFact"),
            ("sig { params(row: T.untyped).returns(SourceSpan) }", &[("row", "T.untyped")], "SourceSpan"),
            ("sig { params(rows: T::Array[T.untyped], metadata: T::Hash[String, T.untyped]).returns(OracleFacts) }", &[("rows", "T::Array[T.untyped]"), ("metadata", "T::Hash[String, T.untyped]")], "OracleFacts"),
            ("sig { params(rows: T::Array[T::Hash[String, T.untyped]]).returns([T::Boolean, T.nilable(String)]) }", &[("rows", "T::Array[T::Hash[String, T.untyped]]")], "[T::Boolean, T.nilable(String)]"),
            ("sig { params(source: String, language: String, override: T.nilable(String)).returns(T.nilable(String)) }", &[("source", "String"), ("language", "String"), ("override", "T.nilable(String)")], "T.nilable(String)"),
            ("sig { params(source: String, span: T.nilable(SourceSpan)).returns(T.nilable([Integer, Integer])) }", &[("source", "String"), ("span", "T.nilable(SourceSpan)")], "T.nilable([Integer, Integer])"),
            ("sig { params(stability: T.nilable(StabilityAnalysis)).returns(T::Boolean) }", &[("stability", "T.nilable(StabilityAnalysis)")], "T::Boolean"),
            ("sig { params(subsumption: SubsumptionAnalysis).returns(T::Boolean) }", &[("subsumption", "SubsumptionAnalysis")], "T::Boolean"),
            ("sig { params(subsumption: SubsumptionAnalysis, gate: EvidenceGate).returns(T::Array[ReviewFinding]) }", &[("subsumption", "SubsumptionAnalysis"), ("gate", "EvidenceGate")], "T::Array[ReviewFinding]"),
            ("sig { params(test: TestObservation, unique_kills: T::Array[String]).returns(T::Array[FindingKind]) }", &[("test", "TestObservation"), ("unique_kills", "T::Array[String]")], "T::Array[FindingKind]"),
            ("sig { params(test_id: String, source: String, line: Integer, framework: String).returns(T::Boolean) }", &[("test_id", "String"), ("source", "String"), ("line", "Integer"), ("framework", "String")], "T::Boolean"),
            ("sig { params(test_ids: T::Array[String]).returns(T::Set[String]) }", &[("test_ids", "T::Array[String]")], "T::Set[String]"),
            ("sig { params(test_ids: T::Array[String], cohort: T.nilable(CohortEvidenceVector)).returns(T::Boolean) }", &[("test_ids", "T::Array[String]"), ("cohort", "T.nilable(CohortEvidenceVector)")], "T::Boolean"),
            ("sig { params(text: String).returns(T::Array[String]) }", &[("text", "String")], "T::Array[String]"),
            ("sig { params(text: String).returns([String, String]) }", &[("text", "String")], "[String, String]"),
            ("sig { params(thread: T.nilable(Thread)).void }", &[("thread", "T.nilable(Thread)")], ""),
            ("sig { params(thread: Thread, io: IO).returns(CapturedOutput) }", &[("thread", "Thread"), ("io", "IO")], "CapturedOutput"),
            ("sig { params(value: T.untyped).returns(Float) }", &[("value", "T.untyped")], "Float"),
            ("sig { params(value: T.untyped).returns(String) }", &[("value", "T.untyped")], "String"),
            ("sig { params(value: T.untyped).returns(T.nilable(Integer)) }", &[("value", "T.untyped")], "T.nilable(Integer)"),
            ("sig { params(value: T.untyped).returns(T.nilable(SourceSpan)) }", &[("value", "T.untyped")], "T.nilable(SourceSpan)"),
            ("sig { params(value: T.untyped, label: String).returns(String) }", &[("value", "T.untyped"), ("label", "String")], "String"),
            ("sig { params(values: T.untyped).returns(T::Array[String]) }", &[("values", "T.untyped")], "T::Array[String]"),
            ("sig { params(wait_thread: T.nilable(Thread)).void }", &[("wait_thread", "T.nilable(Thread)")], ""),
            ("sig { params(wait_thread: Thread, signal: String).void }", &[("wait_thread", "Thread"), ("signal", "String")], ""),
            ("sig { params(wait_thread: Thread, timeout_seconds: Float).returns(T.nilable(Process::Status)) }", &[("wait_thread", "Thread"), ("timeout_seconds", "Float")], "T.nilable(Process::Status)"),
            ("sig { returns(#{candidate[\"type\"]}", &[], ""),
            ("sig { returns(#{type}", &[], ""),
            ("sig { returns(CounterfactualResult) }", &[], "CounterfactualResult"),
            ("sig { returns(Coverage) }", &[], "Coverage"),
            ("sig { returns(EvidenceCompleteness) }", &[], "EvidenceCompleteness"),
            ("sig { returns(Integer) }", &[], "Integer"),
            ("sig { returns(String) }", &[], "String"),
            ("sig { returns(T.nilable(String)) }", &[], "T.nilable(String)"),
            ("sig { returns(T::Array[IndexedKillSet]) }", &[], "T::Array[IndexedKillSet]"),
            ("sig { returns(T::Array[OracleFact]) }", &[], "T::Array[OracleFact]"),
            ("sig { returns(T::Array[T::Hash[String, String]]) }", &[], "T::Array[T::Hash[String, String]]"),
            ("sig { returns(T::Boolean) }", &[], "T::Boolean"),
            ("sig { returns(T::Hash[String, Integer]) }", &[], "T::Hash[String, Integer]"),
            ("sig { returns(T::Hash[String, T.untyped]) }", &[], "T::Hash[String, T.untyped]"),
            ("sig { returns(T::Hash[String, T::Array[String]]) }", &[], "T::Hash[String, T::Array[String]]"),
            ("sig { returns(TYPE) }", &[], "TYPE"),
            ("sig { void }", &[], ""),
            ("sig{\")\n        return nil unless stripped.start_with?(\"#\") || stripped.empty? || stripped == \"end\"\n      end\n      nil\n    end\n\n    def typed_ivar_initialized_before?(path, line_number, ivar)\n      lines = StaticAnalysis.source_lines(File.join(root, path))\n      return true if lines.first(line_number - 1).any? { |prior| typed_ivar_line?(prior, ivar) }", &[], ""),
        ];
        let mut disagreed = Vec::new();
        for (sig, expected_params, expected_return) in cases {
            let got: Vec<(String, String)> = param_entries(sig);
            let want: Vec<(String, String)> = expected_params
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect();
            if got != want {
                disagreed.push(format!("params {sig}: {got:?} != {want:?}"));
            }
            if return_type(sig).unwrap_or("") != *expected_return {
                disagreed.push(format!("return {sig}"));
            }
        }
        assert!(disagreed.is_empty(), "{} disagreements: {:?}", disagreed.len(), disagreed);
    }
