# typed: strict

require "digest"
require "pathname"
require "sorbet-runtime"
require "tempfile"

require_relative "../ffi/c_header_importer"
require_relative "formatter"

# Generates a reviewable, portable CLEAR declaration file from a C header.
# CHeaderImporter owns ABI translation; Formatter owns every layout decision.
class CFFIGenerator
  extend T::Sig

  class Error < StandardError; end

  GENERATED_MARKER = "# Generated by clear c-ffi. Do not edit this file directly."

  sig { params(header: String, output: String, library: String).returns(String) }
  def self.generate(header:, output:, library:)
    raise Error, "C ABI library name cannot be empty" if library.empty?

    output_dir = File.expand_path(File.dirname(output))
    raise Error, "Output directory does not exist: #{output_dir}" unless Dir.exist?(output_dir)

    header_path = File.expand_path(header)
    raise Error, "C header not found: #{header_path}" unless File.file?(header_path)

    relative_header = Pathname.new(header_path).relative_path_from(Pathname.new(output_dir)).to_s
    declarations = CHeaderImporter.import(relative_header, library, source_dir: output_dir)
    digest = Digest::SHA256.file(header_path).hexdigest
    raw = <<~CLEAR
      #{GENERATED_MARKER}
      # Source: #{relative_header}
      # Header-SHA256: #{digest}
      # Link: #{library}

      #{declarations}
    CLEAR
    Formatter.format(raw) || raise(Error, "Formatter returned no C FFI output")
  rescue ArgumentError => e
    raise Error, "Could not make the header path relative to the output: #{e.message}"
  end

  sig { params(output: String, content: String, force: T::Boolean).returns(Symbol) }
  def self.write(output:, content:, force:)
    if File.exist?(output)
      return :unchanged if File.binread(output) == content
      unless force
        raise Error, "Refusing to overwrite #{output}; pass --force or use --check"
      end
    end

    output_dir = File.expand_path(File.dirname(output))
    Tempfile.create([".clear-c-ffi-", ".tmp"], output_dir) do |temporary|
      temporary.binmode
      temporary.write(content)
      temporary.flush
      temporary.fsync
      temporary.close
      File.rename(temporary.path, output)
    end
    :written
  rescue SystemCallError => e
    raise Error, "Could not write #{output}: #{e.message}"
  end

  sig { params(output: String, content: String).returns(T::Boolean) }
  def self.current?(output:, content:)
    File.file?(output) && File.binread(output) == content
  end
end
