# Combinatorial fuzz-program generator for the CLEAR transpiler.
#
# Templates live under tools/fuzz/templates/. Each template registers itself with
# FuzzGenerator.register, declaring its parameter cells (the matrix it owns) and
# a renderer that turns a cell into a complete .cht source string.

class FuzzGenerator
  TEMPLATES = {}

  Template = Struct.new(:name, :cells, :renderer, keyword_init: true)

  def self.register(name, cells:, &renderer)
    raise "duplicate template #{name}" if TEMPLATES.key?(name)
    TEMPLATES[name] = Template.new(name: name, cells: cells, renderer: renderer)
  end

  def initialize(seed:)
    @rng = Random.new(seed)
    load_templates!
  end

  def load_templates!
    Dir[File.expand_path('templates/*.rb', __dir__)].sort.each { |f| require f }
    raise "no templates loaded" if TEMPLATES.empty?
  end

  def full_matrix
    TEMPLATES.flat_map do |name, t|
      t.cells.map { |params| { template: name, params: params } }
    end
  end

  def sample(n)
    matrix = full_matrix
    return matrix if n >= matrix.size
    matrix.sample(n, random: @rng)
  end

  # Returns a hash: { source: <cht text>, expected: :pass | :compile_error | :in_dev }.
  # :in_dev cells are skipped by the runner — they reserve space in the matrix
  # for features not yet landed (e.g., LEND) so the matrix counts stay stable.
  def emit(tuple)
    t = TEMPLATES.fetch(tuple[:template])
    cell = tuple[:params].dup
    expected = cell.delete(:expected) || :pass
    src = t.renderer.call(cell)
    header = "# AUTOGENERATED by tools/fuzz — template=#{tuple[:template]} expected=#{expected} params=#{cell.inspect}\n"
    { source: header + src, expected: expected }
  end
end
