# Combinatorial fuzz-program generator for the CLEAR transpiler.
#
# Templates live under tools/fuzz/templates/. Each template registers itself with
# FuzzGenerator.register, declaring its parameter cells (the matrix it owns) and
# a renderer that turns a cell into a complete .clear source string.

class FuzzGenerator
  TEMPLATES = {}

  Template = Struct.new(:name, :cells, :renderer, keyword_init: true)

  def self.register(name, cells:, &renderer)
    raise "duplicate template #{name}" if TEMPLATES.key?(name)
    invalid = cells.find { |cell| !%i[pass compile_error].include?(cell.fetch(:expected, :pass)) }
    if invalid
      raise "invalid fuzz expectation: template=#{name} cell=#{invalid.inspect}; expected pass or compile_error"
    end
    TEMPLATES[name] = Template.new(name: name, cells: cells, renderer: renderer)
  end

  def initialize(seed:)
    @rng = Random.new(seed)
    load_templates!
  end

  def load_templates!
    Dir[File.expand_path('templates/*.rb', __dir__)].sort.each { |f| require f }
    raise "no templates loaded" if TEMPLATES.empty?
    require_relative 'semantic_migration'
    SemanticMigration.adopt!(TEMPLATES)
  end

  def full_matrix
    TEMPLATES.flat_map do |name, t|
      t.cells.map { |params| { template: name, params: params } }
    end
  end

  def sample(n)
    matrix = full_matrix
    return matrix if n >= matrix.size
    matrix.sample(n, random: @rng)
  end

  # Returns a hash:
  #   { source: <text>, expected: :pass | :compile_error,
  #     kind: :clear | :mir_checker, error_code: Symbol | nil,
  #     diagnostic_code_required: true | false }.
  def emit(tuple)
    t = TEMPLATES.fetch(tuple[:template])
    cell = tuple[:params].dup
    expected = cell.delete(:expected) || :pass
    rendered = t.renderer.call(cell)
    meta = rendered.is_a?(Hash) ? rendered : { source: rendered }
    src = meta.fetch(:source)
    kind = meta.fetch(:kind, :clear)
    header = "# AUTOGENERATED by tools/fuzz — template=#{tuple[:template]} expected=#{expected} params=#{cell.inspect}\n"
    {
      source: header + src,
      expected: expected,
      kind: kind,
      error_code: meta[:error_code],
      diagnostic_code_required: meta.fetch(:diagnostic_code_required, false),
    }
  end
end
