# frozen_string_literal: true

source "https://rubygems.org"

gem "decomplex", path: "../decomplex", require: false
gem "espalier", path: "../espalier", require: false
gem "fact-mine", path: "../fact-mine", require: false

gemspec
gem "boobytrap", path: "../boobytrap", require: false
