Array:
  get: constant
  size: constant
  isEmpty: constant
  first: constant
  last: constant
  add: constant
  removeLast: constant
  contains: linear_scan
  indexOf: linear_scan
  lastIndexOf: linear_scan
  map: linear_materialize
  filter: linear_materialize
  reversed: linear_materialize
  toList: linear_materialize
  sorted: sort
Hash:
  get: constant
  put: constant
  containsKey: constant
  size: constant
  isEmpty: constant
  keys: constant
  values: constant
Set:
  add: constant
  remove: constant
  contains: constant
  size: constant
  isEmpty: constant
String:
  endsWith: linear_scan
  length: constant
  contains: linear_scan
  indexOf: linear_scan
  lastIndexOf: linear_scan
  split: linear_materialize
  startsWith: linear_scan
  substring: linear_materialize
