Array:
  append: constant
  pop: constant
  extend: linear_scan
  insert: linear_scan
  remove: linear_scan
  reverse: linear_scan
  clear: linear_scan
  count: linear_scan
  index: linear_scan
  copy: linear_materialize
  sort: sort
Hash:
  get: constant
  pop: constant
  setdefault: constant
  copy: linear_materialize
  update: linear_scan
  clear: linear_scan
  keys: constant
  values: constant
  items: constant
Set:
  add: constant
  discard: constant
  remove: constant
  copy: linear_materialize
  update: linear_scan
  clear: linear_scan
str:
  count: linear_scan
  find: linear_scan
  index: linear_scan
  startswith: linear_scan
  replace: linear_materialize
  split: linear_materialize
  strip: linear_materialize
String:
  count: linear_scan
  find: linear_scan
  index: linear_scan
  startswith: linear_scan
  replace: linear_materialize
  split: linear_materialize
  strip: linear_materialize
