use super::super::Language;

#[derive(Clone, Copy)]
pub(crate) struct FalseSimplicityLexicon {
    pub(crate) dispatch_mids: &'static [&'static str],
    pub(crate) meta_mids: &'static [&'static str],
    pub(crate) method_obj_mids: &'static [&'static str],
    pub(crate) io_consts: &'static [&'static str],
    pub(crate) io_bare: &'static [&'static str],
    pub(crate) dir_context: &'static [&'static str],
    pub(crate) context_pairs: &'static [(&'static str, &'static [&'static str])],
    pub(crate) context_bare: &'static [&'static str],
    pub(crate) callback_set: &'static [&'static str],
    pub(crate) core_consts: &'static [&'static str],
}

const EMPTY: &[&str] = &[];
const EMPTY_PAIRS: &[(&str, &[&str])] = &[];
const COMMON_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
];

const RUBY_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    ("Time", &["now", "current"]),
    ("Date", &["today", "current"]),
    ("DateTime", &["now", "current"]),
    ("Process", &["pid", "ppid", "uid", "gid", "euid"]),
    ("Thread", &["current", "list", "main"]),
    ("Fiber", &["current"]),
    ("Random", &["rand", "bytes"]),
    ("GC", &["stat", "count"]),
    ("ObjectSpace", &["each_object", "count_objects"]),
];
const PYTHON_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    ("time", &["time", "monotonic", "perf_counter"]),
    ("datetime", &["now", "today", "utcnow"]),
    ("random", &["random", "randint", "randrange", "choice"]),
];
const JS_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    ("Date", &["now"]),
    ("Math", &["random"]),
    ("performance", &["now"]),
];
const GO_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    ("time", &["Now", "Since", "Until"]),
    ("rand", &["Int", "Intn", "Float64", "Read"]),
];
const RUST_CONTEXT_PAIRS: &[(&str, &[&str])] = &[("SystemTime", &["now"]), ("Instant", &["now"])];
const ZIG_CONTEXT_PAIRS: &[(&str, &[&str])] =
    &[("time", &["timestamp", "nanoTimestamp", "milliTimestamp"])];
const LUA_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    ("os", &["time", "clock", "date", "getenv"]),
    ("math", &["random"]),
];
const CPP_CONTEXT_PAIRS: &[(&str, &[&str])] =
    &[("chrono", &["now"]), ("random_device", &["operator()"])];
const CSHARP_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    ("DateTime", &["Now", "UtcNow", "Today"]),
    ("Guid", &["NewGuid"]),
    ("Random", &["Next", "NextDouble"]),
];
const JAVA_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    (
        "System",
        &["currentTimeMillis", "nanoTime", "getenv", "getProperty"],
    ),
    ("Instant", &["now"]),
    ("UUID", &["randomUUID"]),
    ("Math", &["random"]),
];
const SWIFT_CONTEXT_PAIRS: &[(&str, &[&str])] = &[("Date", &["now"]), ("UUID", &["init"])];
const KOTLIN_CONTEXT_PAIRS: &[(&str, &[&str])] = &[
    (
        "System",
        &["currentTimeMillis", "nanoTime", "getenv", "getProperty"],
    ),
    ("Instant", &["now"]),
    ("UUID", &["randomUUID"]),
    ("Random", &["nextInt", "nextLong", "nextDouble"]),
];

const RUBY_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "reentrant",
    "subscribe",
    "callback",
    "hook",
];
const GO_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "Lock",
    "Unlock",
    "RLock",
    "RUnlock",
    "Do",
    "Go",
    "Add",
    "Done",
    "Wait",
];
const RUST_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "read",
    "write",
    "spawn",
    "await",
];
const ZIG_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "spawn",
    "wait",
    "signal",
];
const C_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "pthread_mutex_lock",
    "pthread_mutex_unlock",
];
const CPP_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "try_lock",
    "wait",
    "notify_one",
    "notify_all",
];
const CSHARP_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "Lock",
    "Monitor",
    "Enter",
    "Exit",
    "Wait",
    "Pulse",
];
const JAVA_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "wait",
    "notify",
    "notifyAll",
    "submit",
    "execute",
];
const SWIFT_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "async",
    "sync",
];
const KOTLIN_CALLBACK_SET: &[&str] = &[
    "transaction",
    "synchronize",
    "lock",
    "with_lock",
    "unlock",
    "mutex",
    "atomic",
    "subscribe",
    "callback",
    "hook",
    "synchronized",
    "launch",
    "async",
    "await",
];

const RUBY_CORE_CONSTS: &[&str] = &[
    "String",
    "Symbol",
    "Integer",
    "Float",
    "Numeric",
    "Rational",
    "Complex",
    "Array",
    "Hash",
    "Set",
    "Range",
    "Struct",
    "Object",
    "BasicObject",
    "Kernel",
    "Module",
    "Class",
    "Comparable",
    "Enumerable",
    "Enumerator",
    "Proc",
    "Method",
    "UnboundMethod",
    "NilClass",
    "TrueClass",
    "FalseClass",
    "Exception",
    "StandardError",
    "RuntimeError",
    "ArgumentError",
    "TypeError",
    "NameError",
    "NoMethodError",
    "IO",
    "File",
    "Dir",
    "Time",
    "Date",
    "DateTime",
    "Regexp",
    "MatchData",
    "Thread",
    "Mutex",
    "Fiber",
    "Process",
    "Math",
    "GC",
    "ObjectSpace",
    "Marshal",
    "Random",
    "Encoding",
];

pub(crate) fn false_simplicity_lexicon(language: Language) -> FalseSimplicityLexicon {
    match language {
        Language::Ruby => FalseSimplicityLexicon {
            dispatch_mids: &[
                "send",
                "__send__",
                "public_send",
                "const_get",
                "constantize",
                "instance_variable_get",
            ],
            meta_mids: &[
                "define_method",
                "define_singleton_method",
                "alias_method",
                "class_eval",
                "module_eval",
                "instance_eval",
                "class_exec",
                "module_exec",
                "instance_exec",
                "eval",
                "const_set",
                "instance_variable_set",
                "remove_method",
                "undef_method",
                "prepend",
                "singleton_class",
                "binding",
            ],
            method_obj_mids: &["method", "public_method", "instance_method"],
            io_consts: &[
                "File",
                "IO",
                "Dir",
                "FileUtils",
                "Open3",
                "Socket",
                "TCPSocket",
                "UDPSocket",
                "TCPServer",
                "UNIXSocket",
                "Tempfile",
                "Pathname",
                "Marshal",
            ],
            io_bare: &[
                "puts",
                "print",
                "warn",
                "gets",
                "readline",
                "readlines",
                "system",
                "exec",
                "spawn",
                "fork",
                "sleep",
                "open",
                "abort",
                "exit",
                "exit!",
            ],
            dir_context: &["pwd", "getwd", "home"],
            context_pairs: RUBY_CONTEXT_PAIRS,
            context_bare: &["rand", "srand"],
            callback_set: RUBY_CALLBACK_SET,
            core_consts: RUBY_CORE_CONSTS,
        },
        Language::Python => FalseSimplicityLexicon {
            dispatch_mids: &[
                "getattr",
                "setattr",
                "hasattr",
                "__getattr__",
                "__setattr__",
                "import_module",
            ],
            meta_mids: &[
                "eval", "exec", "compile", "type", "globals", "locals", "vars", "setattr",
                "delattr",
            ],
            method_obj_mids: &["method"],
            io_consts: &[
                "Path",
                "pathlib",
                "os",
                "sys",
                "subprocess",
                "socket",
                "shutil",
            ],
            io_bare: &["print", "input", "open", "exec", "eval"],
            dir_context: &["getcwd", "home"],
            context_pairs: PYTHON_CONTEXT_PAIRS,
            context_bare: &["random", "randint", "randrange"],
            callback_set: COMMON_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::JavaScript | Language::TypeScript => FalseSimplicityLexicon {
            dispatch_mids: &["eval", "Function", "call", "apply", "bind"],
            meta_mids: &[
                "eval",
                "Function",
                "defineProperty",
                "defineProperties",
                "setPrototypeOf",
            ],
            method_obj_mids: &["method"],
            io_consts: &["console", "Console", "fs", "process", "Deno", "Bun"],
            io_bare: &["setTimeout", "setInterval", "fetch", "require", "import"],
            dir_context: EMPTY,
            context_pairs: JS_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: COMMON_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Go => FalseSimplicityLexicon {
            dispatch_mids: &[
                "Call",
                "CallSlice",
                "Method",
                "MethodByName",
                "ValueOf",
                "TypeOf",
            ],
            meta_mids: &["Call", "CallSlice", "MethodByName", "New", "MakeFunc"],
            method_obj_mids: &["method"],
            io_consts: &["os", "io", "ioutil", "fs", "net", "http", "exec", "syscall"],
            io_bare: &["panic", "print", "println", "recover"],
            dir_context: &["Getwd", "UserHomeDir"],
            context_pairs: GO_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: GO_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Rust => FalseSimplicityLexicon {
            dispatch_mids: &[
                "downcast",
                "downcast_ref",
                "downcast_mut",
                "call",
                "call_mut",
                "call_once",
            ],
            meta_mids: &["transmute", "from_raw_parts", "from_raw_parts_mut"],
            method_obj_mids: &["method"],
            io_consts: &["std", "tokio", "fs", "env", "process", "net", "io"],
            io_bare: &["panic", "todo", "unimplemented", "unreachable"],
            dir_context: &["current_dir", "home_dir"],
            context_pairs: RUST_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: RUST_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Zig => FalseSimplicityLexicon {
            dispatch_mids: &["field", "fieldParentPtr", "ptrCast", "alignCast", "call"],
            meta_mids: &[
                "typeInfo",
                "TypeOf",
                "ptrCast",
                "intFromPtr",
                "ptrFromInt",
                "eval",
            ],
            method_obj_mids: &["method"],
            io_consts: &[
                "std", "os", "fs", "process", "net", "Thread", "Mutex", "Atomic",
            ],
            io_bare: &["panic", "unreachable"],
            dir_context: EMPTY,
            context_pairs: ZIG_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: ZIG_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Lua => FalseSimplicityLexicon {
            dispatch_mids: &["load", "loadfile", "dofile", "require", "rawget", "rawset"],
            meta_mids: &[
                "setmetatable",
                "getmetatable",
                "debug",
                "eval",
                "load",
                "loadfile",
            ],
            method_obj_mids: &["method"],
            io_consts: &["io", "os", "debug", "package"],
            io_bare: &["print", "error", "assert", "require", "collectgarbage"],
            dir_context: EMPTY,
            context_pairs: LUA_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: COMMON_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::C => FalseSimplicityLexicon {
            dispatch_mids: &["dlsym", "dlopen", "GetProcAddress"],
            meta_mids: &["setjmp", "longjmp", "va_start", "va_arg"],
            method_obj_mids: &["method"],
            io_consts: &["FILE", "DIR", "pthread", "mutex", "atomic"],
            io_bare: &[
                "printf", "fprintf", "fopen", "open", "read", "write", "close", "system", "exec",
                "abort", "exit", "assert",
            ],
            dir_context: &["getcwd", "getenv"],
            context_pairs: EMPTY_PAIRS,
            context_bare: &["rand", "time", "clock"],
            callback_set: C_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Cpp => FalseSimplicityLexicon {
            dispatch_mids: &[
                "dynamic_cast",
                "typeid",
                "any_cast",
                "get_if",
                "visit",
                "invoke",
            ],
            meta_mids: &["reinterpret_cast", "const_cast", "dlsym", "dlopen"],
            method_obj_mids: &["method"],
            io_consts: &[
                "std",
                "filesystem",
                "fstream",
                "iostream",
                "thread",
                "mutex",
                "atomic",
            ],
            io_bare: &["throw", "abort", "exit", "assert", "system"],
            dir_context: &["current_path"],
            context_pairs: CPP_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: CPP_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::CSharp => FalseSimplicityLexicon {
            dispatch_mids: &[
                "Invoke",
                "GetMethod",
                "GetProperty",
                "GetField",
                "Activator",
                "CreateInstance",
            ],
            meta_mids: &["Invoke", "GetType", "Reflection", "Emit", "DynamicMethod"],
            method_obj_mids: &["method"],
            io_consts: &[
                "Console",
                "File",
                "Directory",
                "Path",
                "Process",
                "Socket",
                "HttpClient",
                "Environment",
            ],
            io_bare: &["throw"],
            dir_context: &["CurrentDirectory", "GetEnvironmentVariable"],
            context_pairs: CSHARP_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: CSHARP_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Java => FalseSimplicityLexicon {
            dispatch_mids: &[
                "invoke",
                "getMethod",
                "getDeclaredMethod",
                "getField",
                "getDeclaredField",
                "forName",
            ],
            meta_mids: &["invoke", "setAccessible", "newInstance", "Proxy"],
            method_obj_mids: &["method"],
            io_consts: &[
                "System",
                "File",
                "Files",
                "Paths",
                "ProcessBuilder",
                "Socket",
                "HttpClient",
                "Thread",
                "Lock",
                "AtomicReference",
            ],
            io_bare: &["throw"],
            dir_context: &["getProperty", "getenv"],
            context_pairs: JAVA_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: JAVA_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Swift => FalseSimplicityLexicon {
            dispatch_mids: &[
                "perform",
                "value",
                "setValue",
                "selector",
                "NSClassFromString",
            ],
            meta_mids: &[
                "Mirror",
                "unsafeBitCast",
                "withUnsafePointer",
                "withUnsafeBytes",
            ],
            method_obj_mids: &["method"],
            io_consts: &[
                "FileManager",
                "Process",
                "URLSession",
                "DispatchQueue",
                "Thread",
                "Lock",
                "NSLock",
            ],
            io_bare: &[
                "print",
                "fatalError",
                "preconditionFailure",
                "assertionFailure",
            ],
            dir_context: &["currentDirectoryPath", "homeDirectoryForCurrentUser"],
            context_pairs: SWIFT_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: SWIFT_CALLBACK_SET,
            core_consts: EMPTY,
        },
        Language::Kotlin => FalseSimplicityLexicon {
            dispatch_mids: &[
                "invoke",
                "call",
                "callBy",
                "memberProperties",
                "declaredMemberFunctions",
            ],
            meta_mids: &[
                "reflection",
                "javaClass",
                "Class",
                "forName",
                "setAccessible",
            ],
            method_obj_mids: &["method"],
            io_consts: &[
                "System",
                "File",
                "Files",
                "Paths",
                "ProcessBuilder",
                "Socket",
                "HttpClient",
                "Thread",
                "Mutex",
                "AtomicReference",
            ],
            io_bare: &["println", "print", "error", "check", "require", "TODO"],
            dir_context: &["getProperty", "getenv"],
            context_pairs: KOTLIN_CONTEXT_PAIRS,
            context_bare: EMPTY,
            callback_set: KOTLIN_CALLBACK_SET,
            core_consts: EMPTY,
        },
    }
}
