# typed: true
# frozen_string_literal: true

# AUTO-GENERATED by bundle exec tools/nil-kill struct-rbi --complete.
# Re-run nil-kill infer/collect before regenerating.

class AST::AllOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::AnyOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::Assert
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def condition; end
  sig { returns(T.untyped) }
  def message; end
end

class AST::AssertRaises
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def kind; end
  sig { returns(T.untyped) }
  def error_name; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::Assignment
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::AverageOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::BatchWindowOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def options; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::BenchmarkStmt
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
  sig { returns(Integer) }
  def iterations; end
end

class AST::BgBlock
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def deferred_drops; end
  sig { returns(T.untyped) }
  def stack_size; end
  sig { returns(T.untyped) }
  def pinned; end
  sig { returns(T.untyped) }
  def parallel; end
  sig { returns(T.untyped) }
  def arena_mode; end
  sig { returns(T.untyped) }
  def can_smash; end
end

class AST::BgStreamBlock
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def deferred_drops; end
  sig { returns(T.untyped) }
  def stack_size; end
end

class AST::BinaryOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def left; end
  sig { returns(T.untyped) }
  def op; end
  sig { returns(T.untyped) }
  def right; end
end

class AST::BindExpr
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def type; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::BlockExpr
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def result; end
end

class AST::BreakNode
  sig { returns(Token) }
  def token; end
end

class AST::CallSiteOverride
  sig { returns(Token) }
  def token; end
  sig { returns(Symbol) }
  def kind; end
  sig { returns(Integer) }
  def n; end
  sig { returns(T.untyped) }
  def inner; end
end

class AST::CapabilityWrap
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(T.untyped) }
  def ownership; end
  sig { returns(T.untyped) }
  def sync; end
  sig { returns(T.untyped) }
  def layout; end
end

class AST::Cast
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(T.untyped) }
  def target; end
end

class AST::CatchBlock
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def catch_clauses; end
  sig { returns(T.untyped) }
  def default_body; end
end

class AST::CloneNode
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::CollectOp
  sig { returns(T.nilable(Token)) }
  def token; end
end

class AST::ConcurrentOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def op; end
  sig { returns(T.untyped) }
  def options; end
end

class AST::ContinueNode
  sig { returns(Lexer::Token) }
  def token; end
end

class AST::Copy
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::CopyNode
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::CountOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::DefaultLit
  sig { returns(Token) }
  def token; end
end

class AST::DieNode
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def status; end
end

class AST::DistinctOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::DoBlock
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def branches; end
end

class AST::EachOp
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
end

class AST::EnumDef
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def variants; end
  sig { returns(Symbol) }
  def visibility; end
end

class AST::ExternFnDecl
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T::Array[T.untyped]) }
  def params; end
  sig { returns(T.untyped) }
  def return_type; end
  sig { returns(T.untyped) }
  def from_module; end
  sig { returns(T::Hash[Symbol, T.untyped]) }
  def effects; end
end

class AST::ExternStructDecl
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(T.untyped) }
  def from_module; end
end

class AST::FindOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::ForEach
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def var_name; end
  sig { returns(T.untyped) }
  def collection; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def deferred_drops; end
  sig { returns(T::Boolean) }
  def is_mutable; end
end

class AST::ForRange
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def var_name; end
  sig { returns(T.untyped) }
  def start_expr; end
  sig { returns(T.untyped) }
  def end_expr; end
  sig { returns(T::Boolean) }
  def inclusive; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def deferred_drops; end
  sig { returns(T.untyped) }
  def mark_per_iter; end
end

class AST::FreezeNode
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::FuncCall
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T::Array[T.untyped]) }
  def args; end
end

class AST::FunctionDef
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T::Array[T.untyped]) }
  def params; end
  sig { returns(T.nilable(T::Array[T.untyped])) }
  def captures; end
  sig { returns(T.untyped) }
  def return_type; end
  sig { returns(T.untyped) }
  def return_lifetime; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def catch_clauses; end
  sig { returns(T.untyped) }
  def default_catch; end
  sig { returns(Symbol) }
  def visibility; end
  sig { returns(T.untyped) }
  def deferred_drops; end
  sig { returns(T.untyped) }
  def uses_frame; end
end

class AST::GetField
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def target; end
  sig { returns(T.untyped) }
  def field; end
end

class AST::GetIndex
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def target; end
  sig { returns(T.untyped) }
  def index; end
end

class AST::HashLit
  sig { returns(Token) }
  def token; end
  sig { returns(T::Hash[T.untyped, T.untyped]) }
  def pairs; end
  sig { returns(Symbol) }
  def storage; end
end

class AST::Identifier
  sig { returns(Token) }
  def token; end
  sig { returns(String) }
  def name; end
end

class AST::IfBind
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def bindings; end
  sig { returns(T.untyped) }
  def then_branch; end
  sig { returns(T.untyped) }
  def else_branch; end
end

class AST::IfStatement
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def condition; end
  sig { returns(T.untyped) }
  def then_branch; end
  sig { returns(T.untyped) }
  def else_branch; end
  sig { returns(T.untyped) }
  def then_drops; end
  sig { returns(T.untyped) }
  def else_drops; end
end

class AST::IndexOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::JoinOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def right_source; end
  sig { returns(T.untyped) }
  def key_expr; end
end

class AST::LambdaLit
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def params; end
  sig { returns(T::Array[T.untyped]) }
  def captures; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(Symbol) }
  def storage; end
  sig { returns(T.untyped) }
  def deferred_drops; end
end

class AST::LetBinding
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def expr; end
end

class AST::LimitOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def count; end
end

class AST::LinkNode
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::ListLit
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def items; end
  sig { returns(Symbol) }
  def storage; end
end

class AST::Literal
  sig { returns(Token) }
  def token; end
  sig { returns(Symbol) }
  def type; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(Symbol) }
  def storage; end
end

class AST::MatchStatement
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T::Array[T.untyped]) }
  def cases; end
  sig { returns(T.untyped) }
  def default_case; end
  sig { returns(T.untyped) }
  def case_drops; end
  sig { returns(T.untyped) }
  def default_drops; end
  sig { returns(T.untyped) }
  def exhaustive; end
  sig { returns(T.untyped) }
  def takes; end
end

class AST::MaxOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::MethodCall
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def object; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T::Array[T.untyped]) }
  def args; end
end

class AST::MinOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::MoveNode
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::NextExpr
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def expr; end
end

class AST::OptionalUnwrap
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def target; end
end

class AST::OrBreak
  sig { returns(Lexer::Token) }
  def token; end
end

class AST::OrExit
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(Symbol) }
  def kind; end
  sig { returns(T.untyped) }
  def error_name; end
  sig { returns(T.untyped) }
  def message; end
end

class AST::OrPass
  sig { returns(Lexer::Token) }
  def token; end
end

class AST::OrPrune
  sig { returns(Lexer::Token) }
  def token; end
end

class AST::OrRaise
  sig { returns(Lexer::Token) }
  def token; end
end

class AST::OrderByOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::PassStmt
  sig { returns(Token) }
  def token; end
end

class AST::Placeholder
  sig { returns(T.nilable(Token)) }
  def token; end
end

class AST::ProfileStmt
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::Program
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def statements; end
end

class AST::Raise
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def kind; end
  sig { returns(T.untyped) }
  def error_name; end
  sig { returns(T.untyped) }
  def message_expr; end
end

class AST::RangeLit
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def start; end
  sig { returns(T.untyped) }
  def finish; end
  sig { returns(T::Boolean) }
  def inclusive; end
end

class AST::RecoverOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def default_expr; end
end

class AST::ReduceOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def initial_value; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::Require
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def path; end
end

class AST::RequireNode
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def path; end
  sig { returns(T.untyped) }
  def namespace; end
  sig { returns(Symbol) }
  def kind; end
end

class AST::ResolveNode
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::ReturnNode
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::SelectOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::ShardOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def key_expr; end
  sig { returns(T.untyped) }
  def target_map; end
end

class AST::ShareNode
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::SkipOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def count; end
end

class AST::Slice
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def target; end
  sig { returns(T.untyped) }
  def start; end
  sig { returns(T.untyped) }
  def end; end
end

class AST::SmashStmt
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::StaticCall
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def type_name; end
  sig { returns(T.untyped) }
  def method_name; end
  sig { returns(T::Array[T.untyped]) }
  def args; end
end

class AST::StringConcat
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def parts; end
end

class AST::StructDef
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(Symbol) }
  def visibility; end
  sig { returns(T::Array[T.untyped]) }
  def type_params; end
end

class AST::StructLit
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(T.untyped) }
  def storage; end
  sig { returns(T.untyped) }
  def type_args; end
end

class AST::StructPattern
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(T::Boolean) }
  def partial; end
end

class AST::StubDecl
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def function_name; end
  sig { returns(Symbol) }
  def kind; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::SumOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::SyncPolicyDecl
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def handlers; end
end

class AST::TakeWhileOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::TapOp
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
end

class AST::TestBlock
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def setup; end
  sig { returns(T::Array[AST::WhenBlock]) }
  def whens; end
end

class AST::TestThat
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def description; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
end

class AST::ThenChain
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def steps; end
end

class AST::ThrowNode
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def value; end
end

class AST::UnaryOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def op; end
  sig { returns(T.untyped) }
  def right; end
end

class AST::UnionDef
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def variants; end
  sig { returns(Symbol) }
  def visibility; end
end

class AST::UnionVariantLit
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def union_name; end
  sig { returns(String) }
  def variant_name; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(Symbol) }
  def storage; end
end

class AST::UnnestOp
  sig { returns(T.nilable(Token)) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::VarDecl
  sig { returns(Token) }
  def token; end
  sig { returns(String) }
  def name; end
  sig { returns(T.untyped) }
  def type; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(T::Boolean) }
  def mutable; end
end

class AST::WhenBlock
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def description; end
  sig { returns(T.untyped) }
  def setup; end
  sig { returns(T::Array[AST::TestThat]) }
  def tests; end
  sig { returns(T.untyped) }
  def benchmarks; end
end

class AST::WhereOp
  sig { returns(Lexer::Token) }
  def token; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::WhileBindLoop
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def condition; end
  sig { returns(T.untyped) }
  def binding_name; end
  sig { returns(T.untyped) }
  def binding_token; end
  sig { returns(T.untyped) }
  def do_branch; end
  sig { returns(T.untyped) }
  def deferred_drops; end
end

class AST::WhileLoop
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def condition; end
  sig { returns(T.untyped) }
  def do_branch; end
  sig { returns(T.untyped) }
  def deferred_drops; end
end

class AST::WindowOp
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def size; end
  sig { returns(T.untyped) }
  def expression; end
end

class AST::WithBlock
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[T.untyped]) }
  def capabilities; end
  sig { returns(T::Array[T.untyped]) }
  def body; end
  sig { returns(T.untyped) }
  def deferred_drops; end
end

class AST::YieldExpr
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def expr; end
end

class AutoConstraintCollector::Slot
  sig { returns(T.untyped) }
  def kind; end
  sig { returns(T.untyped) }
  def fn_name; end
  sig { returns(T.untyped) }
  def index; end
  sig { returns(T.untyped) }
  def decl_node; end
  sig { returns(T.untyped) }
  def sources; end
  sig { returns(T.untyped) }
  def shape; end
  sig { returns(T.untyped) }
  def auto_token; end
end

class AutoUnifier::Ambiguity
  sig { returns(T.untyped) }
  def slot; end
  sig { returns(T.untyped) }
  def observed_types; end
  sig { returns(T.untyped) }
  def sources; end
end

class AutoUnifier::Resolution
  sig { returns(T.untyped) }
  def slot; end
  sig { returns(T.untyped) }
  def type; end
  sig { returns(T.untyped) }
  def sources; end
end

class AutoUnifier::Result
  sig { returns(T.untyped) }
  def resolved; end
  sig { returns(T.untyped) }
  def ambiguous; end
  sig { returns(T.untyped) }
  def unresolved; end
end

class BinaryOpResult
  sig { returns(T.untyped) }
  def type; end
  sig { returns(T.untyped) }
  def left_coercion; end
  sig { returns(T.untyped) }
  def right_coercion; end
  sig { returns(T.untyped) }
  def storage; end
  sig { returns(T.untyped) }
  def error; end
end

class Capabilities::Conflict
  sig { returns(T::Array[T.untyped]) }
  def set_a; end
  sig { returns(T::Array[T.untyped]) }
  def set_b; end
  sig { returns(T.untyped) }
  def message; end
end

class CapabilityHelper::CaptureAnalysis
  sig { returns(T.untyped) }
  def has_local; end
  sig { returns(T.untyped) }
  def has_rc; end
  sig { returns(T.untyped) }
  def has_shared; end
  sig { returns(T.untyped) }
  def has_sharded; end
  sig { returns(T.untyped) }
  def has_affine_locked; end
  sig { returns(T.untyped) }
  def has_outer_ref; end
  sig { returns(T.untyped) }
  def has_non_escaping_capture; end
  sig { returns(T.untyped) }
  def captures; end
  sig { returns(T.untyped) }
  def capture_symbols; end
  sig { returns(T.untyped) }
  def close_patterns; end
  sig { returns(T.untyped) }
  def pointer_captures; end
  sig { returns(T.untyped) }
  def string_captures; end
  sig { returns(T.untyped) }
  def resource_captures; end
  sig { returns(T.untyped) }
  def site_moved; end
  sig { returns(T.untyped) }
  def site_copied; end
  sig { returns(T.untyped) }
  def strategies; end
  sig { returns(T.untyped) }
  def heap_promote_names; end
  sig { returns(T.untyped) }
  def move_mark_names; end
  sig { returns(T.untyped) }
  def alloc_mark_entries; end
end

class CaptureStrategy::ByValue
  sig { returns(String) }
  def zig_type; end
  sig { returns(String) }
  def ctx_init_name; end
end

class CaptureStrategy::CaptureSiteInfo
  sig { returns(T.untyped) }
  def copied_names; end
  sig { returns(T.untyped) }
  def moved_names; end
end

class CaptureStrategy::FreshHeapCopy
  sig { returns(String) }
  def zig_type; end
  sig { returns(String) }
  def ctx_init_name; end
  sig { returns(Symbol) }
  def alloc_sym; end
end

class CaptureStrategy::MoveInto
  sig { returns(String) }
  def zig_type; end
  sig { returns(String) }
  def ctx_init_name; end
  sig { returns(String) }
  def source_name; end
end

class CaptureStrategy::RcClone
  sig { returns(String) }
  def zig_type; end
  sig { returns(String) }
  def ctx_init_name; end
end

class CaptureStrategy::Refuse
  sig { returns(Symbol) }
  def reason; end
  sig { returns(String) }
  def owner_name; end
end

class CompilerFrontend::Result
  sig { returns(T.untyped) }
  def ast; end
  sig { returns(SemanticAnnotator) }
  def annotator; end
  sig { returns(T.untyped) }
  def fn_nodes; end
  sig { returns(T.untyped) }
  def fn_sigs; end
  sig { returns(T.untyped) }
  def struct_schemas; end
  sig { returns(T.untyped) }
  def enum_schemas; end
  sig { returns(T.untyped) }
  def union_schemas; end
  sig { returns(T.untyped) }
  def moved_guard_info; end
end

class FiberCtxBuilder::CaptureSpec
  sig { returns(T.untyped) }
  def name; end
  sig { returns(String) }
  def field_type_zig; end
  sig { returns(T.untyped) }
  def init_value_zig; end
  sig { returns(T.any(MIR::AddressOf, MIR::Ident)) }
  def init_value_mir; end
  sig { returns(T.untyped) }
  def dupe_decl_zig; end
  sig { returns(T.untyped) }
  def body_cleanup_zig; end
end

class FiberCtxBuilder::Result
  sig { returns(T.untyped) }
  def specs; end
  sig { returns(T.untyped) }
  def capture_map; end
  sig { returns(T.untyped) }
  def capture_symbols; end
end

class FixableHelper::AnchorToken
  sig { returns(Integer) }
  def line; end
  sig { returns(Integer) }
  def column; end
end

class FsmOps::AddrOf
  sig { returns(T.untyped) }
  def expr; end
end

class FsmOps::AllocExpr
  sig { returns(String) }
  def elem_type; end
  sig { returns(FsmOps::LocalRef) }
  def count; end
end

class FsmOps::ArgRef
  sig { returns(Integer) }
  def idx; end
end

class FsmOps::AssignField
  sig { returns(String) }
  def field; end
  sig { returns(T.untyped) }
  def value; end
end

class FsmOps::BinOp
  sig { returns(String) }
  def op; end
  sig { returns(MIR::FieldGet) }
  def left; end
  sig { returns(MIR::Lit) }
  def right; end
end

class FsmOps::CallExpr
  sig { returns(String) }
  def fn; end
  sig { returns(T.untyped) }
  def args; end
  sig { returns(T::Boolean) }
  def is_try; end
end

class FsmOps::DeferFreeField
  sig { returns(String) }
  def field; end
end

class FsmOps::ErrDeferCall
  sig { returns(String) }
  def fn; end
  sig { returns(T::Array[FsmOps::StateField]) }
  def args; end
end

class FsmOps::ErrDeferFreeField
  sig { returns(String) }
  def field; end
end

class FsmOps::IfFieldSubLtZeroReturnCall
  sig { returns(String) }
  def field; end
  sig { returns(String) }
  def sub; end
  sig { returns(String) }
  def return_fn; end
  sig { returns(T::Array[FsmOps::SubField]) }
  def return_args; end
end

class FsmOps::IntCast
  sig { returns(String) }
  def zig_type; end
  sig { returns(T.untyped) }
  def expr; end
end

class FsmOps::IoSubmit
  sig { returns(Symbol) }
  def verb; end
  sig { returns(T.untyped) }
  def waiter; end
  sig { returns(T.untyped) }
  def extra_args; end
end

class FsmOps::LetConst
  sig { returns(String) }
  def name; end
  sig { returns(String) }
  def zig_type; end
  sig { returns(FsmOps::IntCast) }
  def value; end
end

class FsmOps::LocalRef
  sig { returns(String) }
  def name; end
end

class FsmOps::SliceUntilIntCast
  sig { returns(FsmOps::StateField) }
  def base; end
  sig { returns(FsmOps::SubField) }
  def end_expr; end
end

class FsmOps::StateField
  sig { returns(String) }
  def name; end
end

class FsmOps::StateFieldDecl
  sig { returns(String) }
  def name; end
  sig { returns(String) }
  def zig_type; end
  sig { returns(String) }
  def init_zig; end
end

class FsmOps::StmtCall
  sig { returns(String) }
  def fn; end
  sig { returns(T.untyped) }
  def args; end
  sig { returns(T::Boolean) }
  def is_try; end
end

class FsmOps::SubField
  sig { returns(FsmOps::StateField) }
  def base; end
  sig { returns(String) }
  def name; end
end

class FsmOps::ZigLit
  sig { returns(String) }
  def zig; end
end

class FsmTransform::Liveness::Result
  sig { returns(T.untyped) }
  def cross_segment_vars; end
end

class FsmTransform::Segments::CondBranch
  sig { returns(T.untyped) }
  def cond_ast; end
  sig { returns(Integer) }
  def then_index; end
  sig { returns(Integer) }
  def else_index; end
end

class FsmTransform::Segments::Done
  sig { returns(T.untyped) }
  def _; end
end

class FsmTransform::Segments::Goto
  sig { returns(Integer) }
  def target_index; end
end

class FsmTransform::Segments::IoSuspend
  sig { returns(T.untyped) }
  def call_node; end
  sig { returns(T.untyped) }
  def stdlib_def; end
  sig { returns(T.untyped) }
  def result_var; end
  sig { returns(T.untyped) }
  def next_index; end
end

class FsmTransform::Segments::LockSuspend
  sig { returns(T.untyped) }
  def with_node; end
  sig { returns(T.untyped) }
  def cap; end
  sig { returns(T.untyped) }
  def prior_caps; end
  sig { returns(T.untyped) }
  def post_acquire_idx; end
  sig { returns(T.untyped) }
  def next_index; end
end

class FsmTransform::Segments::LoopBack
  sig { returns(Integer) }
  def target_index; end
end

class FsmTransform::Segments::NextSuspend
  sig { returns(T.untyped) }
  def promise_ast; end
  sig { returns(T.untyped) }
  def result_var; end
  sig { returns(T.untyped) }
  def next_index; end
end

class FsmTransform::Segments::Segment
  sig { returns(Integer) }
  def index; end
  sig { returns(T::Array[T.untyped]) }
  def stmts; end
  sig { returns(T.untyped) }
  def tail; end
end

class LSP::Analyzer::Result
  sig { returns(T.untyped) }
  def findings; end
  sig { returns(T.untyped) }
  def fatal_error; end
end

class LSP::Analyzer::SyntheticFinding
  sig { returns(T.untyped) }
  def level; end
  sig { returns(T.untyped) }
  def message; end
  sig { returns(T.untyped) }
  def token; end
  sig { returns(T.untyped) }
  def category; end
  sig { returns(T.untyped) }
  def fixes; end
end

class LSP::Analyzer::SyntheticToken
  sig { returns(T.untyped) }
  def line; end
  sig { returns(T.untyped) }
  def column; end
  sig { returns(T.untyped) }
  def value; end
end

class LSP::DocumentStore::Document
  sig { returns(T.untyped) }
  def uri; end
  sig { returns(T.untyped) }
  def text; end
  sig { returns(T.untyped) }
  def version; end
end

class Lexer::Token
  sig { returns(Symbol) }
  def type; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(Integer) }
  def line; end
  sig { returns(Integer) }
  def column; end
end

class LockHelper::LockEdge
  sig { returns(T.untyped) }
  def held; end
  sig { returns(T.untyped) }
  def acquired; end
  sig { returns(T.untyped) }
  def site_token; end
  sig { returns(T.untyped) }
  def fn_name; end
  sig { returns(T.untyped) }
  def opted_out; end
end

class MIR::AddressOf
  sig { returns(T.untyped) }
  def expr; end
end

class MIR::Alloc
  sig { returns(Token) }
  def token; end
  sig { returns(String) }
  def name; end
  sig { returns(T.untyped) }
  def kind; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::AllocMark
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def alloc; end
  sig { returns(T.untyped) }
  def type_info; end
end

class MIR::AllocSlice
  sig { returns(T.untyped) }
  def elem_type; end
  sig { returns(T.untyped) }
  def len; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::AllocatorRef
  sig { returns(Symbol) }
  def kind; end
end

class MIR::ArrayInit
  sig { returns(String) }
  def elem_type; end
  sig { returns(String) }
  def count; end
  sig { returns(T.untyped) }
  def items; end
end

class MIR::BatchWindowFlush
  sig { returns(String) }
  def window; end
  sig { returns(String) }
  def batch_var; end
  sig { returns(String) }
  def elem_zig; end
  sig { returns(String) }
  def result_var; end
  sig { returns(T.untyped) }
  def value_expr; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::BatchWindowPush
  sig { returns(String) }
  def window; end
  sig { returns(MIR::Ident) }
  def item_expr; end
  sig { returns(String) }
  def batch_var; end
  sig { returns(String) }
  def elem_zig; end
  sig { returns(String) }
  def result_var; end
  sig { returns(T.untyped) }
  def value_expr; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::BgBlock
  sig { returns(String) }
  def code; end
  sig { returns(T.untyped) }
  def captures; end
  sig { returns(T.untyped) }
  def run_body; end
  sig { returns(T.untyped) }
  def fsm_structure; end
end

class MIR::BinOp
  sig { returns(T.untyped) }
  def op; end
  sig { returns(T.untyped) }
  def left; end
  sig { returns(T.untyped) }
  def right; end
end

class MIR::BlockExpr
  sig { returns(T.untyped) }
  def label; end
  sig { returns(T.untyped) }
  def body; end
end

class MIR::BreakStmt
  sig { returns(T.untyped) }
  def label; end
  sig { returns(T.untyped) }
  def value; end
end

class MIR::Call
  sig { returns(T.untyped) }
  def callee; end
  sig { returns(T.untyped) }
  def args; end
  sig { returns(T.any(T::Boolean, T::Hash[T.untyped, T.untyped])) }
  def try_wrap; end
  sig { returns(T.untyped) }
  def heap_provenance; end
end

class MIR::CapWrap
  sig { returns(T.untyped) }
  def inner; end
  sig { returns(T.untyped) }
  def zig_base; end
  sig { returns(Symbol) }
  def strategy; end
  sig { returns(T.untyped) }
  def sync_fn; end
  sig { returns(T.untyped) }
  def sync_type; end
  sig { returns(T.untyped) }
  def own_fn; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::Cast
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T.untyped) }
  def target_type; end
  sig { returns(Symbol) }
  def method; end
end

class MIR::CatchWrapper
  sig { returns(String) }
  def code; end
  sig { returns(T.untyped) }
  def error_reassigns; end
  sig { returns(T.untyped) }
  def clause_bodies; end
  sig { returns(T.untyped) }
  def clause_meta; end
  sig { returns(T.untyped) }
  def has_default; end
end

class MIR::Cleanup
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def cleanup_entry; end
end

class MIR::Comment
  sig { returns(String) }
  def text; end
end

class MIR::Comptime
  sig { returns(T.any(MIR::InlineBc, MIR::InlineZig)) }
  def expr; end
end

class MIR::ConcatStr
  sig { returns(T.untyped) }
  def parts; end
  sig { returns(Symbol) }
  def alloc; end
  sig { returns(T.untyped) }
  def rt_expr; end
end

class MIR::Conditional
  sig { returns(T.any(MIR::BinOp, MIR::Ident)) }
  def cond; end
  sig { returns(T.any(MIR::BinOp, MIR::Cast, MIR::Ident)) }
  def then_val; end
  sig { returns(T.any(MIR::BinOp, MIR::Ident, MIR::Lit)) }
  def else_val; end
end

class MIR::ContainerInit
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(Symbol) }
  def strategy; end
  sig { returns(T.untyped) }
  def alloc; end
  sig { returns(T.untyped) }
  def capacity; end
end

class MIR::ContinueStmt
  sig { returns(T.untyped) }
  def unused; end
end

class MIR::DeepCopy
  sig { returns(T.untyped) }
  def source; end
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(T.untyped) }
  def elem_type; end
  sig { returns(Symbol) }
  def strategy; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::DeferStmt
  sig { returns(T.untyped) }
  def body; end
end

class MIR::Deref
  sig { returns(T.any(MIR::Deref, MIR::FieldGet, MIR::Ident)) }
  def expr; end
end

class MIR::DestroyPtr
  sig { returns(T.any(MIR::FieldGet, MIR::Ident)) }
  def ptr; end
  sig { returns(T.any(MIR::Ident, Symbol)) }
  def alloc; end
end

class MIR::DoBlock
  sig { returns(String) }
  def code; end
  sig { returns(T.untyped) }
  def branch_bodies; end
end

class MIR::Drop
  sig { returns(Token) }
  def token; end
  sig { returns(String) }
  def name; end
  sig { returns(T.untyped) }
  def kind; end
  sig { returns(T.untyped) }
  def alloc; end
  sig { returns(T::Boolean) }
  def has_moved_guard; end
  sig { returns(T.untyped) }
  def type_info; end
  sig { returns(T.untyped) }
  def resource_close_zig; end
  sig { returns(T.untyped) }
  def source_node; end
end

class MIR::DupeSlice
  sig { returns(T.untyped) }
  def source; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::EnumDef
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def variants; end
  sig { returns(T.untyped) }
  def visibility; end
end

class MIR::ErrCleanup
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def cleanup_entry; end
end

class MIR::ErrDeferStmt
  sig { returns(T.untyped) }
  def body; end
end

class MIR::EscapePromote
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(Symbol) }
  def strategy; end
  sig { returns(T.untyped) }
  def data; end
  sig { returns(String) }
  def rt_expr; end
  sig { returns(T.untyped) }
  def elem_type; end
end

class MIR::ExprStmt
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T.untyped) }
  def discard; end
end

class MIR::FieldCleanup
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def target_name; end
  sig { returns(String) }
  def field; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::FieldCleanupMark
  sig { returns(T.untyped) }
  def target_name; end
  sig { returns(String) }
  def field; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::FieldDef
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(T.untyped) }
  def default; end
end

class MIR::FieldGet
  sig { returns(T.untyped) }
  def object; end
  sig { returns(T.untyped) }
  def field; end
end

class MIR::FnDef
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.any(T::Array[MIR::Param], T::Array[T.untyped])) }
  def params; end
  sig { returns(T.untyped) }
  def ret_type; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(T.untyped) }
  def visibility; end
  sig { returns(T::Boolean) }
  def can_fail; end
  sig { returns(T.untyped) }
  def comptime_params; end
end

class MIR::FnRef
  sig { returns(T.untyped) }
  def name; end
end

class MIR::ForStmt
  sig { returns(T.untyped) }
  def iter; end
  sig { returns(T.untyped) }
  def capture; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(T.untyped) }
  def index_capture; end
  sig { returns(T.untyped) }
  def mark_per_iter; end
  sig { returns(T.untyped) }
  def tight; end
end

class MIR::FrameRestore
  sig { returns(String) }
  def rt_expr; end
end

class MIR::FrameSave
  sig { returns(String) }
  def rt_expr; end
end

class MIR::FreeSlice
  sig { returns(T.any(MIR::FieldGet, MIR::Ident)) }
  def slice; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::FreezeExpr
  sig { returns(MIR::FieldGet) }
  def inner; end
  sig { returns(T.untyped) }
  def zig_base; end
end

class MIR::FsmB1Body
  sig { returns(T.untyped) }
  def blk_label; end
  sig { returns(T.untyped) }
  def ctx_struct; end
  sig { returns(T.untyped) }
  def spawn_setup; end
end

class MIR::FsmB1CtxStruct
  sig { returns(T.untyped) }
  def type_name; end
  sig { returns(T.untyped) }
  def promise_zig; end
  sig { returns(T.untyped) }
  def captures_decl_zig; end
  sig { returns(T.untyped) }
  def run_body; end
end

class MIR::FsmCtxStruct
  sig { returns(T.untyped) }
  def type_name; end
  sig { returns(T.untyped) }
  def promise_zig; end
  sig { returns(T.untyped) }
  def captures_decl_zig; end
  sig { returns(T.untyped) }
  def state_decls; end
  sig { returns(T.untyped) }
  def promoted_field_decls; end
  sig { returns(T.untyped) }
  def step0; end
  sig { returns(T.untyped) }
  def step1; end
  sig { returns(T.untyped) }
  def resume_fn; end
end

class MIR::FsmDispatch
  sig { returns(T.untyped) }
  def ctx_id; end
  sig { returns(T::Enumerator[[T.untyped, Integer]]) }
  def arms; end
  sig { returns(T::Boolean) }
  def uses_loop_label; end
end

class MIR::FsmGenericBody
  sig { returns(T.untyped) }
  def blk_label; end
  sig { returns(MIR::FsmGenericCtxStruct) }
  def ctx_struct; end
  sig { returns(MIR::FsmSpawnSetup) }
  def spawn_setup; end
end

class MIR::FsmGenericCtxStruct
  sig { returns(T.untyped) }
  def type_name; end
  sig { returns(T.untyped) }
  def promise_zig; end
  sig { returns(T.untyped) }
  def captures_decl_zig; end
  sig { returns(T.untyped) }
  def extra_field_decls; end
  sig { returns(T.untyped) }
  def promoted_field_decls; end
  sig { returns(T::Array[MIR::FsmMemberFn]) }
  def member_fns; end
  sig { returns(MIR::FsmDispatch) }
  def resume_fn_zig; end
  sig { returns(T.untyped) }
  def destroy_extra_zig; end
end

class MIR::FsmIoBody
  sig { returns(T.untyped) }
  def blk_label; end
  sig { returns(T.untyped) }
  def ctx_struct; end
  sig { returns(T.untyped) }
  def spawn_setup; end
end

class MIR::FsmMemberFn
  sig { returns(T.untyped) }
  def fn_name; end
  sig { returns(T.untyped) }
  def ctx_id; end
  sig { returns(T.untyped) }
  def bg_rt; end
  sig { returns(String) }
  def rt_suppress_zig; end
  sig { returns(T.untyped) }
  def body_stmts; end
  sig { returns(T.untyped) }
  def extra_prologue_zig; end
end

class MIR::FsmSpawnSetup
  sig { returns(T.untyped) }
  def alloc_var; end
  sig { returns(String) }
  def alloc_expr_zig; end
  sig { returns(T.untyped) }
  def promise_var; end
  sig { returns(T.untyped) }
  def promise_zig; end
  sig { returns(T.untyped) }
  def promoted_decls_zig; end
  sig { returns(T.untyped) }
  def ctx_var; end
  sig { returns(T.untyped) }
  def ctx_type; end
  sig { returns(String) }
  def ctx_init_zig; end
  sig { returns(String) }
  def spawn_call_zig; end
  sig { returns(T.untyped) }
  def rt_name; end
  sig { returns(T.untyped) }
  def profile_site_id; end
  sig { returns(Integer) }
  def profile_dispatch_id; end
  sig { returns(String) }
  def profile_site_comment; end
end

class MIR::FsmStateArm
  sig { returns(T.untyped) }
  def index; end
  sig { returns(T.untyped) }
  def pre_body_skip; end
  sig { returns(T.untyped) }
  def pre_body_zig; end
  sig { returns(T.untyped) }
  def body_fn_name; end
  sig { returns(T.untyped) }
  def err_cleanups; end
  sig { returns(T.untyped) }
  def tail; end
end

class MIR::FsmStep
  sig { returns(T.untyped) }
  def index; end
  sig { returns(T.untyped) }
  def ctx_id; end
  sig { returns(T.untyped) }
  def bg_rt; end
  sig { returns(T.untyped) }
  def rt_suppress_zig; end
  sig { returns(T.untyped) }
  def body_stmts; end
end

class MIR::FsmStructure
  sig { returns(T.untyped) }
  def captures; end
  sig { returns(T.untyped) }
  def state_fields; end
  sig { returns(T.untyped) }
  def steps; end
  sig { returns(T.untyped) }
  def finalize_cleanups; end
  sig { returns(T.untyped) }
  def ctx_id; end
  sig { returns(T.untyped) }
  def result_aliases_finalized; end
end

class MIR::FsmTailCondJump
  sig { returns(T.noreturn) }
  def cond_zig; end
  sig { returns(Integer) }
  def then_step; end
  sig { returns(Integer) }
  def else_step; end
end

class MIR::FsmTailCondSkip
  sig { returns(T.untyped) }
  def cond_zig; end
  sig { returns(T.untyped) }
  def skip_step; end
end

class MIR::FsmTailDone
  sig { returns(T.untyped) }
  def _; end
end

class MIR::FsmTailJump
  sig { returns(Integer) }
  def next_step; end
end

class MIR::FsmTailLockTry
  sig { returns(T.untyped) }
  def try_method; end
  sig { returns(T.untyped) }
  def lock_field_ref; end
  sig { returns(T.untyped) }
  def ok_step; end
  sig { returns(T.untyped) }
  def wait_step; end
  sig { returns(T.untyped) }
  def error_step; end
end

class MIR::FsmTailRegisterYield
  sig { returns(T.untyped) }
  def next_step; end
  sig { returns(T.untyped) }
  def register_zig; end
  sig { returns(T.untyped) }
  def yield_reason; end
end

class MIR::FsmTailRetryOrError
  sig { returns(T.untyped) }
  def retries; end
  sig { returns(T.untyped) }
  def retry_step; end
  sig { returns(T.untyped) }
  def fail_step; end
end

class MIR::FsmTailWokenCheck
  sig { returns(T.untyped) }
  def ok_step; end
  sig { returns(T.untyped) }
  def error_step; end
end

class MIR::FsmTailYield
  sig { returns(T.untyped) }
  def next_step; end
  sig { returns(T.untyped) }
  def yield_reason; end
end

class MIR::HasField
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T.untyped) }
  def field; end
end

class MIR::HeapCreate
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(T.any(MIR::DeepCopy, MIR::ItemsAccess, MIR::StructInit)) }
  def init; end
  sig { returns(Symbol) }
  def alloc; end
  sig { returns(String) }
  def label; end
end

class MIR::Ident
  sig { returns(T.untyped) }
  def name; end
end

class MIR::IfBindStmt
  sig { returns(T.untyped) }
  def bindings; end
  sig { returns(T::Array[T.any(T.untyped, T.untyped)]) }
  def then_body; end
  sig { returns(T.untyped) }
  def else_body; end
end

class MIR::IfChain
  sig { returns(T::Enumerator[T.untyped]) }
  def branches; end
  sig { returns(T.untyped) }
  def default_body; end
end

class MIR::IfOptional
  sig { returns(T.untyped) }
  def optional; end
  sig { returns(String) }
  def capture; end
  sig { returns(T.untyped) }
  def then_expr; end
  sig { returns(MIR::Lit) }
  def else_expr; end
end

class MIR::IfStmt
  sig { returns(T.untyped) }
  def cond; end
  sig { returns(T.untyped) }
  def then_body; end
  sig { returns(T.untyped) }
  def else_body; end
end

class MIR::Import
  sig { returns(T.untyped) }
  def alias_name; end
  sig { returns(String) }
  def module_path; end
  sig { returns(T.untyped) }
  def member; end
end

class MIR::IndexGet
  sig { returns(T.untyped) }
  def object; end
  sig { returns(T.untyped) }
  def index; end
end

class MIR::IndexInsert
  sig { returns(MIR::Ident) }
  def map; end
  sig { returns(MIR::Ident) }
  def key_expr; end
  sig { returns(MIR::Ident) }
  def value_expr; end
  sig { returns(String) }
  def key_zig_type; end
  sig { returns(String) }
  def elem_zig_type; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::InlineBc
  sig { returns(T.untyped) }
  def op; end
  sig { returns(T.untyped) }
  def args; end
  sig { returns(T.untyped) }
  def stdlib_def; end
end

class MIR::InlineZig
  sig { returns(T.untyped) }
  def code; end
  sig { returns(String) }
  def reason; end
  sig { returns(T.untyped) }
  def ownership_contract; end
  sig { returns(T.untyped) }
  def stdlib_def; end
  sig { returns(T.untyped) }
  def allocs; end
  sig { returns(T.untyped) }
  def target_var; end
end

class MIR::ItemsAccess
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T::Boolean) }
  def safe; end
end

class MIR::IterRange
  sig { returns(T.untyped) }
  def start; end
  sig { returns(T.untyped) }
  def end_val; end
end

class MIR::LambdaExpr
  sig { returns(MIR::FnDef) }
  def fn_def; end
  sig { returns(T.untyped) }
  def captures; end
end

class MIR::Let
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def init; end
  sig { returns(T.untyped) }
  def mutable; end
  sig { returns(T.untyped) }
  def annotation; end
  sig { returns(T.untyped) }
  def suppression; end
end

class MIR::ListItems
  sig { returns(T.untyped) }
  def list; end
end

class MIR::ListLength
  sig { returns(T.untyped) }
  def expr; end
end

class MIR::Lit
  sig { returns(T.untyped) }
  def value; end
end

class MIR::MakeList
  sig { returns(T.untyped) }
  def elem_type; end
  sig { returns(T.untyped) }
  def items; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::MethodCall
  sig { returns(T.untyped) }
  def receiver; end
  sig { returns(T.untyped) }
  def method; end
  sig { returns(T.untyped) }
  def args; end
  sig { returns(T::Boolean) }
  def try_wrap; end
end

class MIR::MoveMark
  sig { returns(T.untyped) }
  def name; end
end

class MIR::MutualThunkTrampoline
  sig { returns(T.untyped) }
  def fn_name; end
  sig { returns(String) }
  def ret_zig; end
  sig { returns(T.untyped) }
  def variants; end
  sig { returns(T.untyped) }
  def initial_variant; end
  sig { returns(T::Array[String]) }
  def initial_fields; end
  sig { returns(T.untyped) }
  def arms; end
  sig { returns(String) }
  def yield_line; end
end

class MIR::Noop
  sig { returns(String) }
  def reason; end
end

class MIR::OptionalUnwrap
  sig { returns(T.untyped) }
  def expr; end
end

class MIR::Orelse
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T.untyped) }
  def fallback; end
end

class MIR::Panic
  sig { returns(String) }
  def message; end
end

class MIR::Param
  sig { returns(T.untyped) }
  def name; end
  sig { returns(String) }
  def zig_type; end
  sig { returns(T.any(T::Boolean, T::Hash[T.untyped, T.untyped])) }
  def pointer_passed; end
end

class MIR::Pipeline
  sig { returns(AST::BinaryOp) }
  def ast_node; end
  sig { returns(T.untyped) }
  def inner; end
  sig { returns(T.untyped) }
  def source_type; end
  sig { returns(T.untyped) }
  def stages; end
  sig { returns(T.untyped) }
  def sink; end
  sig { returns(T.untyped) }
  def sink_alloc; end
end

class MIR::PolymorphicMutate
  sig { returns(String) }
  def cell_zig; end
  sig { returns(String) }
  def rt; end
  sig { returns(T.untyped) }
  def alias_zig; end
  sig { returns(String) }
  def bare_t_zig; end
  sig { returns(T.untyped) }
  def body; end
end

class MIR::PolymorphicMutateFlow
  sig { returns(String) }
  def cell_zig; end
  sig { returns(String) }
  def rt; end
  sig { returns(T.untyped) }
  def alias_zig; end
  sig { returns(String) }
  def bare_t_zig; end
  sig { returns(String) }
  def ret_zig; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(T.untyped) }
  def guard_cond; end
  sig { returns(T.untyped) }
  def guard_fail_body; end
end

class MIR::Program
  sig { returns(T.untyped) }
  def items; end
end

class MIR::Promote
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(Symbol) }
  def strategy; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(T.untyped) }
  def elem_type; end
end

class MIR::PubConst
  sig { returns(String) }
  def name; end
  sig { returns(String) }
  def value; end
end

class MIR::RangeLit
  sig { returns(T.untyped) }
  def start; end
  sig { returns(T.untyped) }
  def end_val; end
  sig { returns(T.untyped) }
  def elem_type; end
end

class MIR::RawBc
  sig { returns(T.untyped) }
  def template; end
  sig { returns(T.untyped) }
  def args; end
  sig { returns(T.untyped) }
  def stdlib_def; end
end

class MIR::RawZig
  sig { returns(T.untyped) }
  def code; end
  sig { returns(String) }
  def reason; end
  sig { returns(T.untyped) }
  def ownership_contract; end
  sig { returns(T.untyped) }
  def stdlib_def; end
end

class MIR::RcDowngrade
  sig { returns(T.untyped) }
  def source; end
  sig { returns(T.untyped) }
  def zig_base; end
  sig { returns(String) }
  def func; end
end

class MIR::RcRetain
  sig { returns(T.untyped) }
  def source; end
  sig { returns(String) }
  def zig_base; end
  sig { returns(String) }
  def func; end
end

class MIR::ReassignCleanup
  sig { returns(Token) }
  def token; end
  sig { returns(String) }
  def name; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::ReassignMark
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def alloc; end
end

class MIR::ReassignWithCleanup
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(String) }
  def zig_type; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::Return
  sig { returns(Token) }
  def token; end
  sig { returns(T::Array[String]) }
  def escaped_vars; end
end

class MIR::ReturnMark
  sig { returns(T::Array[String]) }
  def escaped_vars; end
end

class MIR::ReturnStmt
  sig { returns(T.untyped) }
  def value; end
end

class MIR::ScopeBlock
  sig { returns(T.untyped) }
  def body; end
end

class MIR::Set
  sig { returns(T.untyped) }
  def target; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(T.untyped) }
  def needs_field_cleanup; end
end

class MIR::ShardedMapGet
  sig { returns(MIR::Deref) }
  def target; end
  sig { returns(T.untyped) }
  def key; end
  sig { returns(T.untyped) }
  def shard_idx; end
  sig { returns(T.untyped) }
  def shard_key; end
  sig { returns(Symbol) }
  def map_kind; end
  sig { returns(T.untyped) }
  def stdlib_def; end
  sig { returns(T.untyped) }
  def key_zig; end
  sig { returns(T.untyped) }
  def val_zig; end
  sig { returns(T.untyped) }
  def resolved_allocs; end
  sig { returns(Symbol) }
  def template_kind; end
end

class MIR::ShardedMapPut
  sig { returns(MIR::Deref) }
  def target; end
  sig { returns(T.untyped) }
  def key; end
  sig { returns(MIR::InlineZig) }
  def value; end
  sig { returns(T.untyped) }
  def shard_idx; end
  sig { returns(T.untyped) }
  def shard_key; end
  sig { returns(T.untyped) }
  def map_kind; end
  sig { returns(T.untyped) }
  def stdlib_def; end
  sig { returns(T.untyped) }
  def key_zig; end
  sig { returns(T.untyped) }
  def val_zig; end
  sig { returns(T.untyped) }
  def resolved_allocs; end
  sig { returns(Symbol) }
  def template_kind; end
end

class MIR::SharePromote
  sig { returns(T.untyped) }
  def source; end
  sig { returns(String) }
  def zig_base; end
  sig { returns(Symbol) }
  def alloc; end
end

class MIR::SliceExpr
  sig { returns(T.untyped) }
  def target; end
  sig { returns(T.any(MIR::Cast, MIR::Ident, MIR::Lit)) }
  def start; end
  sig { returns(T.untyped) }
  def end_expr; end
  sig { returns(T.untyped) }
  def elem_type; end
end

class MIR::SnapshotMultiTxn
  sig { returns(String) }
  def cells_tuple; end
  sig { returns(String) }
  def rt; end
  sig { returns(String) }
  def alloc; end
  sig { returns(String) }
  def alias_decls; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(String) }
  def conflict_action; end
  sig { returns(T.untyped) }
  def retries; end
  sig { returns(T.untyped) }
  def with_label; end
end

class MIR::SnapshotRead
  sig { returns(String) }
  def cell_unwrap; end
  sig { returns(String) }
  def rt; end
  sig { returns(T.untyped) }
  def alias_zig; end
  sig { returns(String) }
  def guard_var; end
  sig { returns(T.untyped) }
  def body; end
end

class MIR::SnapshotTransaction
  sig { returns(String) }
  def cell_unwrap; end
  sig { returns(String) }
  def rt; end
  sig { returns(String) }
  def alloc; end
  sig { returns(T.untyped) }
  def alias_zig; end
  sig { returns(String) }
  def bare_t_zig; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(String) }
  def conflict_action; end
  sig { returns(T.untyped) }
  def retries; end
  sig { returns(T.untyped) }
  def with_label; end
  sig { returns(T.untyped) }
  def is_atomic_ptr; end
end

class MIR::SoaFieldAccess
  sig { returns(MIR::Ident) }
  def soa_expr; end
  sig { returns(T.untyped) }
  def field_name; end
end

class MIR::Sort
  sig { returns(T.untyped) }
  def elem_type; end
  sig { returns(MIR::FieldGet) }
  def items_expr; end
  sig { returns(T.untyped) }
  def key_a; end
  sig { returns(T.untyped) }
  def key_b; end
end

class MIR::StreamSpawn
  sig { returns(T.untyped) }
  def captures; end
  sig { returns(T.untyped) }
  def body; end
end

class MIR::StreamYield
  sig { returns(T.untyped) }
  def value; end
end

class MIR::StructDef
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def fields; end
  sig { returns(T.untyped) }
  def methods; end
  sig { returns(T.untyped) }
  def visibility; end
end

class MIR::StructInit
  sig { returns(T.untyped) }
  def zig_type; end
  sig { returns(T.any(T::Array[T.untyped], T::Array[T::Hash[T.untyped, T.untyped]])) }
  def fields; end
end

class MIR::Suppress
  sig { returns(T.untyped) }
  def name; end
end

class MIR::SuppressCleanup
  sig { returns(Token) }
  def token; end
  sig { returns(T.untyped) }
  def name; end
end

class MIR::SuspendDescriptor
  sig { returns(T.untyped) }
  def setup_stmts; end
  sig { returns(T.untyped) }
  def bind_stmts; end
  sig { returns(T.any(MIR::FsmTailRegisterYield, MIR::FsmTailYield)) }
  def tail; end
  sig { returns(T.any(T::Array[String], T::Array[T.untyped])) }
  def ctx_field_decls; end
  sig { returns(String) }
  def result_var; end
  sig { returns(T.untyped) }
  def result_zig_type; end
end

class MIR::SwitchStmt
  sig { returns(T.untyped) }
  def subject; end
  sig { returns(T.untyped) }
  def arms; end
  sig { returns(T.untyped) }
  def default_body; end
end

class MIR::TailCall
  sig { returns(T.untyped) }
  def callee; end
  sig { returns(T.untyped) }
  def args; end
end

class MIR::TestDef
  sig { returns(String) }
  def name; end
  sig { returns(T.untyped) }
  def body; end
end

class MIR::ThunkTrampoline
  sig { returns(T.untyped) }
  def fn_name; end
  sig { returns(String) }
  def ret_zig; end
  sig { returns(T::Array[String]) }
  def param_field_decls; end
  sig { returns(T::Array[String]) }
  def param_init_fields; end
  sig { returns(T.untyped) }
  def base_cases; end
  sig { returns(T.untyped) }
  def recurse_arg_inits; end
  sig { returns(T.untyped) }
  def combine_lhs_zig; end
  sig { returns(T.untyped) }
  def op_zig; end
  sig { returns(String) }
  def yield_line; end
end

class MIR::TransferMark
  sig { returns(String) }
  def name; end
  sig { returns(Symbol) }
  def target; end
end

class MIR::TryCatch
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T.untyped) }
  def catch_body; end
  sig { returns(T.untyped) }
  def capture; end
  sig { returns(T.untyped) }
  def heap_provenance; end
end

class MIR::TryExpr
  sig { returns(T.untyped) }
  def expr; end
end

class MIR::TryOrPanic
  sig { returns(T.untyped) }
  def expr; end
  sig { returns(T.untyped) }
  def panic_msg; end
end

class MIR::TypeAlias
  sig { returns(T.untyped) }
  def name; end
  sig { returns(String) }
  def target; end
end

class MIR::TypeSentinel
  sig { returns(Symbol) }
  def extreme; end
  sig { returns(T.untyped) }
  def zig_type; end
end

class MIR::UnaryOp
  sig { returns(String) }
  def op; end
  sig { returns(T.untyped) }
  def operand; end
end

class MIR::Undef
  sig { returns(T.untyped) }
  def zig_type; end
end

class MIR::UnionTypeDef
  sig { returns(T.untyped) }
  def name; end
  sig { returns(T.untyped) }
  def variants; end
  sig { returns(T.untyped) }
  def visibility; end
end

class MIR::UnionVariantGet
  sig { returns(T.untyped) }
  def object; end
  sig { returns(String) }
  def variant; end
  sig { returns(String) }
  def zig_type; end
end

class MIR::WeakUpgrade
  sig { returns(T.untyped) }
  def source; end
  sig { returns(T.untyped) }
  def zig_base; end
  sig { returns(String) }
  def func; end
end

class MIR::WhileStmt
  sig { returns(T.untyped) }
  def cond; end
  sig { returns(T.untyped) }
  def body; end
  sig { returns(T.untyped) }
  def capture; end
  sig { returns(T.untyped) }
  def update; end
  sig { returns(T.untyped) }
  def mark_per_iter; end
  sig { returns(T.untyped) }
  def tight; end
end

class MIR::WithMatchDispatch
  sig { returns(String) }
  def cell_zig; end
  sig { returns(T.untyped) }
  def arms; end
end

class MIRPass::WalkCtx
  sig { returns(T.untyped) }
  def bindings; end
  sig { returns(T.untyped) }
  def promo; end
end

class ModuleImporter::CompiledModule
  sig { returns(AST::Program) }
  def ast; end
  sig { returns(T.untyped) }
  def global_scope; end
  sig { returns(T.untyped) }
  def transpiled_body; end
  sig { returns(String) }
  def source_dir; end
  sig { returns(T::Hash[Symbol, Schemas::StructSchema]) }
  def struct_schemas; end
  sig { returns(T::Hash[Symbol, Schemas::UnionSchema]) }
  def union_schemas; end
  sig { returns(T.untyped) }
  def enum_schemas; end
  sig { returns(T.untyped) }
  def type_defs; end
end

class OwnershipDataflow::DataflowStep
  sig { returns(T.untyped) }
  def state; end
  sig { returns(T.untyped) }
  def consumed; end
end

class OwnershipDataflow::OwnerEntry
  sig { returns(T.untyped) }
  def state; end
  sig { returns(T.untyped) }
  def allocator; end
  sig { returns(T.untyped) }
  def needs_cleanup; end
end

class OwnershipGraph::Edge
  sig { returns(T.untyped) }
  def from; end
  sig { returns(T.untyped) }
  def to; end
  sig { returns(T.untyped) }
  def kind; end
end

class OwnershipGraph::Node
  sig { returns(T.untyped) }
  def path; end
  sig { returns(T.untyped) }
  def kind; end
  sig { returns(T.untyped) }
  def state; end
  sig { returns(T.untyped) }
  def type_info; end
  sig { returns(T.untyped) }
  def scope_depth; end
  sig { returns(T.untyped) }
  def line; end
  sig { returns(T.untyped) }
  def move_line; end
  sig { returns(T.untyped) }
  def move_col; end
  sig { returns(T.untyped) }
  def move_action; end
  sig { returns(T.untyped) }
  def move_consumer_param_type; end
end

class TestLowering::TestThatEnv
  sig { returns(T.untyped) }
  def ctx; end
  sig { returns(T.untyped) }
  def when_block; end
  sig { returns(T.untyped) }
  def when_desc; end
  sig { returns(T.untyped) }
  def tag_suffix; end
  sig { returns(T.untyped) }
  def stub_mir; end
  sig { returns(T.untyped) }
  def when_setup_mir; end
  sig { returns(T.untyped) }
  def when_before_each_mir; end
  sig { returns(T.untyped) }
  def when_after_each_mir; end
  sig { returns(T.untyped) }
  def let_ast_map; end
end

class ThunkTransform::RecursiveSplitter::MutualPlan
  sig { returns(T.untyped) }
  def base_cases; end
  sig { returns(T.untyped) }
  def target_fn; end
  sig { returns(T.untyped) }
  def target_args; end
  sig { returns(T.untyped) }
  def final_return; end
end

class ThunkTransform::RecursiveSplitter::MutualThunkPlan
  sig { returns(T.untyped) }
  def cycle_fns; end
  sig { returns(T.untyped) }
  def own_plan; end
end

class ThunkTransform::RecursiveSplitter::Plan
  sig { returns(T.untyped) }
  def base_cases; end
  sig { returns(T.untyped) }
  def combine_lhs; end
  sig { returns(T.untyped) }
  def combine_op; end
  sig { returns(T.untyped) }
  def recurse_args; end
  sig { returns(T.untyped) }
  def final_return; end
end
