# typed: true

# Minimal stub declarations so Sorbet's static name resolver does not
# emit `Did you mean Socket?`-style false positives on user-defined
# classes when files default to `# typed: false`. As files are flipped
# to `# typed: true` / `# typed: strict` per the self-host prep tracker
# (TODO.md), these stubs become redundant and can be tightened or
# replaced with real signatures generated by `tapioca` once the
# Ruby 3.2 + tapioca 0.19 incompat (`coerce_and_check_module_types`
# crash on init) is resolved.

# Lexer::Token is a Struct(:type, :value, :line, :column) defined in
# src/ast/lexer.rb. Re-declare under its canonical Lexer:: namespace
# so autogen sigs that record `Lexer::Token` (from runtime) match what
# the AST::Locatable RBI override exposes via `node.token`.
class Lexer
end

class Lexer::Token
  sig { returns(Symbol) }
  def type; end
  sig { returns(T.untyped) }
  def value; end
  sig { returns(Integer) }
  def line; end
  sig { returns(Integer) }
  def column; end
end

# Top-level alias: existing references in this RBI keep working.
Token = Lexer::Token

# AST::Locatable is mixed into AST nodes; declare Kernel methods so
# Sorbet doesn't trip over `node.is_a?(...)`, `node.class`, etc. when
# helper modules type-narrow against AST::Locatable receivers. The
# real Object methods are available at runtime via the host class.
module AST::Locatable
  include Kernel

  # Every AST node is a Struct + includes Locatable; expose the Struct
  # surface (`node[:member]`) so generic AST walkers type-check.
  sig { params(member: T.untyped).returns(T.untyped) }
  def [](member); end

  # First Struct member on every AST node. Always non-nil in
  # production (parser passes a Token at every construction site).
  # Specs that pass `nil` are excluded from Sorbet via sorbet/config.
  sig { returns(Token) }
  def token; end
end
