# typed: true
# frozen_string_literal: true

# AUTO-GENERATED by bundle exec tools/nil-kill struct-rbi.
# Re-run nil-kill infer/collect before regenerating.

class Capabilities::Conflict
  sig { returns(String) }
  def message; end
  sig { returns(T::Array[T.untyped]) }
  def set_a; end
  sig { returns(T::Array[T.untyped]) }
  def set_b; end
end

class FiberCtxBuilder::CaptureSpec
  sig { returns(String) }
  def field_type_zig; end
end

class FmtVerifier::Result
  sig { returns(T::Boolean) }
  def ok; end
end

class Formatter::FormatLexer::Token
  sig { returns(Integer) }
  def col; end
  sig { returns(Integer) }
  def line; end
  sig { returns(String) }
  def raw; end
  sig { returns(Symbol) }
  def type; end
end

class FsmOps::BinOp
  sig { returns(MIR::FieldGet) }
  def left; end
  sig { returns(String) }
  def op; end
  sig { returns(MIR::Lit) }
  def right; end
end

class FsmOps::IntCast
  sig { returns(String) }
  def zig_type; end
end

class FsmTransform::Segments::CondBranch
  sig { returns(Integer) }
  def else_index; end
  sig { returns(Integer) }
  def then_index; end
end

class FsmTransform::Segments::Goto
  sig { returns(Integer) }
  def target_index; end
end

class FsmTransform::Segments::LoopBack
  sig { returns(Integer) }
  def target_index; end
end

class FsmTransform::Segments::Segment
  sig { returns(Integer) }
  def index; end
  sig { returns(T::Array[T.untyped]) }
  def stmts; end
end
