#!/usr/bin/env ruby
# Branch-gap report for the memory-safety-critical lowering passes.
#
# Reads coverage/.resultset.json (SimpleCov with `enable_coverage :branch`,
# regenerated by COVERAGE=1 ./clear test transpile-tests/ and/or the spec
# + fuzz corpus collated via spec/collate_coverage.rb) and prints, for each
# pass file, every decision sub-branch that NO program in the corpus ever
# took.
#
# This is deliberately NOT a percentage chase. A never-taken branch in the
# escape / frame / lowering code is a concrete "no .cht program exercises
# this decision" finding — each one is a forensic candidate of the
# bug-#1/#2/#9 class (a shape the corpus never produces). A branch being
# *taken* says nothing about whether it's correct for every shape; that's
# what mutation + the structural generator are for. This report only
# answers the floor question honestly: which decisions are dead to the
# whole corpus.
#
# Usage: ruby tools/branch_gap_report.rb [extra/file.rb ...]

require "json"

ROOT = File.expand_path("..", __dir__)
RESULTSET = File.join(ROOT, "coverage", ".resultset.json")

DEFAULT_FILES = %w[
  src/mir/mir_lowering.rb
  src/mir/control_flow.rb
  src/mir/escape_analysis.rb
].freeze

abort "no #{RESULTSET} — run COVERAGE=1 ./clear test transpile-tests/" unless File.exist?(RESULTSET)

data = JSON.parse(File.read(RESULTSET))
# Merge branch counts across every resultset entry (RSpec workers,
# transpile-tests-PID, clear-cli-PID): a branch is "taken" if ANY entry
# took it.
merged = Hash.new
data.each_value do |entry|
  (entry["coverage"] || {}).each do |path, cov|
    next unless cov.is_a?(Hash) && cov["branches"]
    dst = (merged[path] ||= {})
    cov["branches"].each do |parent, arms|
      d = (dst[parent] ||= Hash.new(0))
      arms.each { |arm, n| d[arm] = d[arm] + (n || 0) }
    end
  end
end

targets = ARGV.empty? ? DEFAULT_FILES : ARGV
grand_total = 0
grand_uncov = 0

targets.each do |rel|
  abspath = File.join(ROOT, rel)
  branches = merged[abspath]
  unless branches
    puts "## #{rel}\n  (no branch data — file not exercised by this corpus at all)\n\n"
    next
  end
  src = File.exist?(abspath) ? File.readlines(abspath) : []
  total = 0
  uncovered = []
  branches.each do |_parent, arms|
    arms.each do |arm, count|
      total += 1
      next unless count.to_i.zero?
      # arm tuple: "[:then, id, start_line, start_col, end_line, end_col]"
      m = arm.gsub(/[\[\]:]/, "").split(",").map(&:strip)
      kind = m[0]
      line = m[2].to_i
      uncovered << [line, kind, (src[line - 1] || "").strip]
    end
  end
  grand_total += total
  grand_uncov += uncovered.size
  pct = total.zero? ? 100.0 : (100.0 * (total - uncovered.size) / total)
  puts format("## %s — %.1f%% branch (%d/%d arms taken)",
              rel, pct, total - uncovered.size, total)
  if uncovered.empty?
    puts "  (every decision arm taken by the corpus)\n\n"
    next
  end
  uncovered.sort_by(&:first).each do |line, kind, text|
    text = text[0, 110]
    puts format("  %s:%-5d  %-6s  %s", rel, line, kind, text)
  end
  puts
end

if grand_total.positive?
  pct = 100.0 * (grand_total - grand_uncov) / grand_total
  puts format("=== TOTAL across %d files: %.1f%% branch (%d uncovered arms) ===",
              targets.size, pct, grand_uncov)
end
