#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require_relative "../src/ast/type"

ROOT = File.expand_path("..", __dir__)
OUT = File.expand_path(File.join(ROOT, "tmp", "nil-kill", "combined-corpus.cht"))
SOURCE_DIRS = %w[examples benchmarks].freeze
EXCLUDE_RE = ENV["NIL_KILL_COMBINE_EXCLUDE"] && Regexp.new(ENV.fetch("NIL_KILL_COMBINE_EXCLUDE"))
LIVE_DATA_EXCLUDES = %w[
  examples/minivm/_bc_runner.cht
  examples/minivm/_scheme_runner.cht
  examples/minivm/bench_pool_ops.cht
  examples/minivm/bench_pool_ops_nosync.cht
  examples/minivm/debugger.cht
  examples/minivm/parser.cht
  examples/minivm/sus-int.cht
  examples/minivm/types.cht
  examples/minivm/vm.cht
  examples/minivm/vtest.cht
].freeze

def prefix_for(path)
  rel = path.delete_suffix(".cht")
  rel.gsub(/[^A-Za-z0-9]+/, "_").gsub(/\A_+|_+\z/, "")
end

def declarations(source)
  source.scan(/^\s*(?:EXTERN\s+)?(FN|STRUCT|UNION|ENUM)\s+([A-Za-z_][A-Za-z0-9_!?]*)\b/i)
end

def main_signature(source)
  match = source.match(/^\s*FN\s+(main!?)(\s*\(\s*\)\s+RETURNS\s+([^\s]+)\s*->)/i)
  match && { name: match[1], return_type: match[3] }
end

def rewrite_code_segment(segment, rename_map)
  rename_map.each do |from, to|
    segment = segment.gsub(/(?<![A-Za-z0-9_])#{Regexp.escape(from)}(?![A-Za-z0-9_])/, to)
  end
  segment
end

def rewrite_references(source, rename_map)
  out = +""
  source.each_line do |line|
    idx = 0
    chunk = +""
    in_string = false
    escape = false

    while idx < line.length
      char = line[idx]
      if !in_string && char == "#"
        out << rewrite_code_segment(chunk, rename_map)
        out << line[idx..]
        break
      end

      if !in_string && char == "\""
        out << rewrite_code_segment(chunk, rename_map)
        chunk = +""
        out << char
        in_string = true
      elsif in_string
        out << char
        if escape
          escape = false
        elsif char == "\\"
          escape = true
        elsif char == "\""
          in_string = false
        end
      else
        chunk << char
      end
      idx += 1
    end

    out << rewrite_code_segment(chunk, rename_map) if idx >= line.length
  end
  out
end

files = SOURCE_DIRS.flat_map do |dir|
  Dir.glob(File.join(ROOT, dir, "**", "*.cht"))
end.sort.reject do |abs_path|
  rel = abs_path.delete_prefix(ROOT + File::SEPARATOR)
  next true if rel.split(File::SEPARATOR).include?("bench.profile")
  # Temporary live-data exclusions for files that do not currently transpile.
  # 06/07 are blocked by the pending BG promise-capture bug; the minivm files
  # are corpus/compiler-cleanup exceptions. The combined corpus is a debug
  # artifact and remains conservative around REQUIRE-heavy examples.
  LIVE_DATA_EXCLUDES.include?(rel) || EXCLUDE_RE&.match?(rel)
end

dispatch = []
body = +"# Generated by tools/clear-nil-kill-combine-cht-corpus.rb\n"
body << "# Temporary nil-kill runtime collection corpus. Do not edit by hand.\n\n"

files.each do |abs_path|
  rel = abs_path.delete_prefix(ROOT + File::SEPARATOR)
  source = File.read(abs_path)
  main = main_signature(source)
  prefix = prefix_for(rel)
  rename_map = declarations(source).to_h do |kind, name|
    renamed =
      if kind.upcase == "FN"
        "nil_kill_#{prefix}__#{name}"
      else
        "NilKill_#{prefix}__#{name}"
      end
    [name, renamed]
  end

  body << "# ===== #{rel} =====\n"
  source = source.lines.map do |line|
    if line.lstrip.start_with?("REQUIRE ")
      "# nil-kill combined corpus skipped duplicate #{line}"
    else
      line
    end
  end.join
  source = rewrite_references(source, rename_map)
  if main
    dispatch << [rename_map.fetch(main[:name]), main[:return_type]]
  else
    body << "# No zero-argument main function found; included without dispatcher entry.\n"
  end
  body << source
  body << "\n\n"
end

body << "# ===== nil-kill combined dispatcher =====\n"
body << "FN main() RETURNS !Void ->\n"
dispatch.each do |name, return_type|
  call = Type.new(return_type).error_union? ? "#{name}() OR RAISE;" : "#{name}();"
  body << "  #{call}\n"
end
body << "  RETURN;\n"
body << "END\n"

FileUtils.mkdir_p(File.dirname(OUT))
File.write(OUT, body)
puts OUT
