#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "pathname"

ROOT = File.expand_path("..", __dir__)
OUT = File.expand_path(File.join(ROOT, "tmp", "nil-kill", "require-corpus.cht"))
SOURCE_DIRS = %w[examples benchmarks].freeze
LIVE_DATA_EXCLUDES = %w[
  examples/minivm/_bc_runner.cht
  examples/minivm/_scheme_runner.cht
  examples/minivm/bench_pool_ops.cht
  examples/minivm/bench_pool_ops_nosync.cht
  examples/minivm/debugger.cht
  examples/minivm/parser.cht
  examples/minivm/sus-int.cht
  examples/minivm/types.cht
  examples/minivm/vtest.cht
].freeze

files = SOURCE_DIRS.flat_map do |dir|
  Dir.glob(File.join(ROOT, dir, "**", "*.cht"))
end.sort.reject do |abs_path|
  rel = abs_path.delete_prefix(ROOT + File::SEPARATOR)
  next true if rel.split(File::SEPARATOR).include?("bench.profile")
  # Temporary live-data exclusions for files that do not currently transpile.
  # The minivm files are corpus/compiler-cleanup exceptions.
  LIVE_DATA_EXCLUDES.include?(rel)
end

out_dir = File.dirname(OUT)
body = +"# Generated by tools/clear-nil-kill-require-cht-corpus.rb\n"
body << "# Temporary nil-kill runtime collection corpus. Do not edit by hand.\n\n"

files.each do |abs_path|
  rel = Pathname.new(abs_path).relative_path_from(Pathname.new(out_dir)).to_s
  body << "REQUIRE #{rel.inspect};\n"
end

body << "\nFN main() RETURNS Void ->\n"
body << "  RETURN;\n"
body << "END\n"

FileUtils.mkdir_p(out_dir)
File.write(OUT, body)
puts OUT
