#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "pathname"

ROOT = File.expand_path("..", __dir__)
OUT = File.expand_path(File.join(ROOT, "tmp", "nil-kill", "require-corpus.clear"))
SOURCE_DIRS = %w[examples benchmarks].freeze
LIVE_DATA_EXCLUDES = %w[
  benchmarks/concurrent/12_false_sharing/bench.clear
  benchmarks/concurrent/13_rwlock_starvation/bench.clear
  benchmarks/concurrent/14_nested_lock/bench.clear
  benchmarks/concurrent/19_atomic_ptr/bench.clear
  benchmarks/inter-clear/03_concurrent_mvcc_vs_rwlock/bench.clear
  benchmarks/inter-clear/04_concurrent_mvcc_fat_struct/bench.clear
  benchmarks/inter-clear/05_concurrent_mvcc_pure_read/bench.clear
  benchmarks/inter-clear/06_concurrent_mvcc_writer_pressure/bench.clear
  examples/minivm/_bc_runner.clear
  examples/minivm/_scheme_runner.clear
  examples/minivm/bench_pool_ops.clear
  examples/minivm/bench_pool_ops_nosync.clear
  examples/minivm/debugger.clear
  examples/minivm/parser.clear
  examples/minivm/sus-int.clear
  examples/minivm/types.clear
  examples/minivm/vm.clear
  examples/minivm/vtest.clear
].freeze

files = SOURCE_DIRS.flat_map do |dir|
  Dir.glob(File.join(ROOT, dir, "**", "*.clear"))
end.sort.reject do |abs_path|
  rel = abs_path.delete_prefix(ROOT + File::SEPARATOR)
  next true if rel.split(File::SEPARATOR).any? { |part| part.end_with?(".profile") }
  # Temporary live-data exclusions for files that do not currently transpile.
  # The minivm files are corpus/compiler-cleanup exceptions.
  LIVE_DATA_EXCLUDES.include?(rel)
end

out_dir = File.dirname(OUT)
body = +"# Generated by tools/clear-nil-kill-require-clear-corpus.rb\n"
body << "# Temporary nil-kill runtime collection corpus. Do not edit by hand.\n\n"

files.each do |abs_path|
  rel = Pathname.new(abs_path).relative_path_from(Pathname.new(out_dir)).to_s
  body << "REQUIRE #{rel.inspect};\n"
end

body << "\nFN main() RETURNS Void ->\n"
body << "  RETURN;\n"
body << "END\n"

FileUtils.mkdir_p(out_dir)
File.write(OUT, body)
puts OUT
