#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate the self-hosted stdlib registry as TYPED CLEAR.
#
# The Ruby registries (STD_LIB, POOL_METHODS, ...) are hash literals, and
# IntrinsicRegistry calls itself a "startup converter" that turns them into
# typed FunctionSignature + IntrinsicEmit objects. CLEAR has no dynamic value
# type -- `Any` lowers to f64 -- so the hash cannot survive translation. This
# runs the converter here, at build time, and emits the typed objects directly,
# which is what the self-hosted annotator reads.
#
#   ruby tools/gen_intrinsic_registry_clear.rb [--out FILE]
#
# Regenerate whenever a registry entry changes; the output is checked in so a
# CLEAR build needs no Ruby.

require 'optparse'
require_relative '../compiler/ruby/annotator/helpers/intrinsic_registry'

module GenIntrinsicRegistryClear
  extend self

  REGISTRIES = {
    STD_LIB: :std_lib,
    POOL_METHODS: :pool_methods,
    SET_METHODS: :set_methods,
    MAP_METHODS: :map_methods,
    INDEX_OPS: :index_ops,
    BUILTIN_OPS: :builtin_ops
  }.freeze

  def main(argv)
    out = File.expand_path('../compiler/src/ast/std_lib_registry.clear', __dir__)
    OptionParser.new do |parser|
      parser.on('--out FILE') { |value| out = File.expand_path(value) }
    end.parse!(argv)

    File.write(out, render)
    warn "wrote #{out} (#{File.read(out).lines.length} lines)"
    0
  end

  def render
    body = +''
    body << HEADER
    REGISTRIES.each do |const, fn_suffix|
      body << render_registry(Object.const_get(const), fn_suffix)
    end
    body << render_dispatch
    body
  end

  HEADER = <<~CLEAR
    REQUIRE "pkg:rtoc_#{'ast/type.clear'.unpack1('H*')}"
    REQUIRE "pkg:rtoc_#{'ast/param.clear'.unpack1('H*')}"
    REQUIRE "pkg:rtoc_#{'annotator/helpers/function_signature.clear'.unpack1('H*')}"
    REQUIRE "pkg:rtoc_#{'annotator/helpers/function_return.clear'.unpack1('H*')}"
    REQUIRE "pkg:rtoc_#{'annotator/helpers/intrinsic_emit.clear'.unpack1('H*')}"
    REQUIRE "pkg:rtoc_#{'annotator/helpers/intrinsic_arg_spec.clear'.unpack1('H*')}"

    # GENERATED by tools/gen_intrinsic_registry_clear.rb -- do not edit.
    #
    # The Ruby registry hashes are the authoring DSL; this is the typed result
    # of IntrinsicRegistry's converter, emitted so the self-hosted annotator
    # reads signatures directly instead of parsing an untyped hash at runtime.

  CLEAR

  def render_registry(registry, fn_suffix)
    entries = IntrinsicRegistry.sigs(registry)
    out = +"PUB FN stdLibRegistry__#{fn_suffix}() RETURNS !{String}[]FunctionSignature@multiowned ->\n"
    out << "  MUTABLE table: {String}[]FunctionSignature@multiowned = {};\n"
    # CLEAR index-assignment takes a VARIABLE index, not a literal.
    out << "  MUTABLE key: String = \"\";\n"
    entries.each do |name, value|
      sigs = Array(value)
      out << "  key = #{quote(name.to_s)};\n"
      out << "  table[key] = [#{sigs.map { |fs| signature_literal(fs) }.join(', ')}];\n"
    end
    out << "  RETURN table;\nEND\n\n"
    out
  end

  def render_dispatch
    arms = REGISTRIES.values.map do |fn_suffix|
      "  IF (name == :#{fn_suffix}) THEN\n    RETURN TRY (stdLibRegistry__#{fn_suffix}());\n  END\n"
    end.join
    <<~CLEAR
      PUB FN stdLibRegistry__table(name: String@symbol) RETURNS !{String}[]FunctionSignature@multiowned ->
      #{arms}  RETURN {};
      END
    CLEAR
  end

  def signature_literal(fs)
    contract = fs.instance_variable_get(:@contract)
    facts = fs.instance_variable_get(:@facts)
    "FunctionSignature{ contract: COPY #{contract_literal(contract)}, " \
      "facts: #{facts_literal(facts)}, generic_bounds: {}, intrinsic_contract: NIL }"
  end

  def contract_literal(contract)
    "Contract{ extern: FALSE, extern_effects: {}, extern_source: NIL, fn_type_params: [], " \
      "intrinsic: TRUE, module_alias: NIL, owner_type: NIL, owner_type_params: [], " \
      "params: [#{contract.params.map { |p| param_literal(p) }.join(', ')}], reentrant: FALSE, " \
      "return_lifetime: [], return_type: #{type_literal(contract.return_type)}, " \
      "type_params: [], visibility: NIL }"
  end

  def param_literal(param)
    "Param{ name: #{quote(param.name.to_s)}, type: #{type_literal(param.type)}, default: NIL, " \
      "mutable: #{opt_bool(param.mutable)}, takes: #{opt_bool(param.takes)}, comptime: NIL, " \
      "name_token: NIL, required: #{opt_bool(param.required)}, sync: #{opt_sym(param.sync)}, " \
      "symbol: NIL, carrier_contract: :none }"
  end

  def facts_literal(facts)
    emit = facts.instance_variable_get(:@emit)
    specs = facts.instance_variable_get(:@intrinsic_arg_specs) || []
    "AnalysisFacts{ needs_rt: #{opt_bool(facts.needs_rt)}, can_fail: #{opt_bool(facts.can_fail)}, " \
      "alloc_fault: #{opt_bool(facts.alloc_fault)}, error_fallible: #{opt_bool(facts.error_fallible)}, " \
      "effects: NIL, return_strategy: #{opt_sym(facts.return_strategy)}, " \
      "stack_tier: #{opt_sym(facts.stack_tier)}, requires: {}, " \
      "heap_carry_return: #{opt_bool(facts.heap_carry_return)}, heap_carry_return_vars: NIL, " \
      "arg_validator: #{opt_sym(facts.arg_validator)}, " \
      "intrinsic_arg_specs: [#{specs.map { |s| arg_spec_literal(s) }.join(', ')}], " \
      "intrinsic_fixed_arg_list: #{bool(facts.intrinsic_fixed_arg_list)}, " \
      "intrinsic_varargs: #{bool(facts.intrinsic_varargs)}, arity: #{opt_int(facts.arity)}, " \
      "emit: #{emit ? emit_literal(emit) : 'NIL'}, " \
      "return_def: #{return_def_literal(facts.instance_variable_get(:@return_def))} }"
  end

  def arg_spec_literal(spec)
    "IntrinsicArgSpec{ name: #{opt_str(spec.name)}, type: #{sym(spec.type)}, " \
      "sync: #{opt_sym(spec.sync)}, ownership: #{opt_sym(spec.ownership)}, " \
      "mutable: #{bool(spec.mutable)}, takes: #{bool(spec.takes)} }"
  end

  def return_def_literal(return_def)
    return 'NIL' unless return_def

    kind = return_def.instance_variable_get(:@kind)
    fixed = return_def.instance_variable_get(:@fixed)
    infer = return_def.instance_variable_get(:@infer)
    "FunctionReturn{ fixed: #{fixed ? type_literal(fixed) : 'NIL'}, infer: #{opt_sym(infer)}, " \
      "kind: Kind.#{camel(kind.serialize)} }"
  end

  # Only the fields the registry actually populates are emitted; the rest take
  # the struct's empty defaults. `borrows` is `:all` everywhere it appears.
  def emit_literal(emit)
    fields = {
      'zig' => str_or_sym(emit.zig),
      'numeric_zig' => str_or_sym(emit.numeric_zig),
      'sharded_zig' => str_or_sym(emit.sharded_zig),
      'shard_direct_zig' => str_or_sym(emit.shard_direct_zig),
      'fsm_setup' => '[]',
      'fsm_state_decls' => '[]',
      'fsm_finish_block' => '[]',
      'fsm_state_finalize' => '[]',
      'fsm_setup_present' => bool(emit.fsm_setup_present),
      'fsm_state_decls_present' => bool(emit.fsm_state_decls_present),
      'fsm_finish_block_present' => bool(emit.fsm_finish_block_present),
      'fsm_state_finalize_present' => bool(emit.fsm_state_finalize_present),
      'fsm_finish_value' => 'NIL',
      'bc' => bool(emit.bc),
      'is_method' => bool(emit.is_method),
      'suspends' => bool(emit.suspends),
      'narrows_collection' => bool(emit.narrows_collection),
      'narrows_receiver_collection' => bool(emit.narrows_receiver_collection),
      'mutates_receiver' => bool(emit.mutates_receiver),
      'allocates' => bool(emit.allocates),
      'takes_value' => bool(emit.takes_value),
      'container_borrow' => bool(emit.container_borrow),
      'tag' => opt_sym(emit.tag),
      'builtin' => opt_sym(emit.builtin),
      'alloc' => opt_sym(emit.alloc),
      'return_alloc' => opt_sym(emit.return_alloc),
      'val_alloc' => opt_sym(emit.val_alloc),
      'key_alloc' => opt_sym(emit.key_alloc),
      'shard_alloc' => opt_sym(emit.shard_alloc),
      'sharded_alloc' => opt_sym(emit.sharded_alloc),
      'borrows' => emit.borrows.nil? ? 'NIL' : "Borrows{ SymbolValue: #{sym(emit.borrows)} }",
      'reject_when' => opt_sym(emit.reject_when),
      'bc_op' => opt_sym(emit.bc_op),
      'error_kind' => opt_sym(emit.error_kind),
      'error_type' => opt_sym(emit.error_type),
      'registry' => opt_sym(emit.registry),
      'elem' => opt_str(emit.elem),
      'lifetime' => "[#{Array(emit.lifetime).map { |l| quote(l.to_s) }.join(', ')}]",
      'reject_error' => opt_str(emit.reject_error),
      'arity' => opt_int(emit.arity),
      'takes_args' => "[#{Array(emit.takes_args).map { |i| "#{i}_i64" }.join(', ')}]"
    }
    nested = %w[eql strcmp cleanup assert array list pool set get string_raw string_symbol
                string_map numeric_map set_collection]
    nested.each do |name|
      value = emit.public_send(name)
      fields[name] = value ? emit_literal(value) : 'NIL'
    end
    "IntrinsicEmit{ #{fields.map { |k, v| "#{k}: #{v}" }.join(', ')} }"
  end

  def type_literal(type)
    return 'TRY (type__new(TypeConstructionInput{ SymbolValue: :Any }))' unless type

    "TRY (type__new(TypeConstructionInput{ StringValue: #{quote(Type.surface_name(type))} }))"
  end

  def str_or_sym(value)
    return 'NIL' if value.nil?
    return "IntrinsicEmitStrOrSym{ SymbolValue: #{sym(value)} }" if value.is_a?(Symbol)

    "IntrinsicEmitStrOrSym{ StringValue: #{quote(value.to_s)} }"
  end

  def camel(value) = value.to_s.split('_').map(&:capitalize).join
  def bool(value) = value ? 'TRUE' : 'FALSE'
  def opt_bool(value) = value.nil? ? 'NIL' : bool(value)
  def opt_int(value) = value.nil? ? 'NIL' : "#{value}_i64"
  # A symbol whose text is not a bare identifier cannot be written `:like_this`.
  def sym(value)
    text = value.to_s
    text.match?(/\A[A-Za-z_][A-Za-z0-9_]*[?!]?\z/) ? ":#{text}" : "symbol(#{quote(text)})"
  end
  def opt_sym(value) = value.nil? ? 'NIL' : sym(value)
  def opt_str(value) = value.nil? ? 'NIL' : quote(value.to_s)
  def quote(value) = "\"#{value.gsub('\\', '\\\\\\\\').gsub('"', '\\"').gsub("\n", '\\n')}\""
end

exit(GenIntrinsicRegistryClear.main(ARGV)) if $PROGRAM_NAME == __FILE__
