#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate the write-side Emittable field rewriter.
#
# emit.rb:1058 is eight lines of Ruby REFLECTION:
#
#   return unless node.is_a?(Struct)
#   node.members.each do |field|
#     value = node[field]
#     next unless value.is_a?(MIR::Emittable) ||
#       (value.is_a?(Array) && value.all? { |c| c.is_a?(MIR::Emittable) })
#     node[field] = rewrite_promoted_fsm_node(value, promoted_names, id)
#   end
#
# CLEAR has no runtime struct reflection: no Struct#members, no node[field]
# get/set. The read half of this already exists as a GENERATED dispatcher --
# emittable__child_exprs in mir.clear, 64 arms built from per-class Ruby
# child_exprs methods. The write half has no Ruby counterpart to translate,
# because Ruby reaches for reflection instead.
#
# So generate it, the same way. This is the faithful realisation of
# Struct#members in a statically typed language: one arm per Emittable variant
# that owns Emittable-typed fields (127 of 184 variants, 190 fields), rebuilding
# the variant with each such field rewritten. Regenerate whenever mir.clear's
# Emittable union or its variant structs change.
$PROGRAM_NAME = 'gen_fsm_struct_rewriter_support'

ROOT = File.expand_path('..', __dir__)
MIR = File.join(ROOT, 'compiler', 'src', 'mir', 'mir.clear')

src = File.read(MIR)
union_line = src.lines.find { |l| l.start_with?('PUB UNION Emittable ') } or abort 'Emittable union not found'
variants = union_line[/\{(.*)\}/, 1].split(',').map do |pair|
  name, type = pair.split(':', 2).map(&:strip)
  [name, type]
end

structs = {}
src.scan(/^PUB STRUCT (\w+) \{([^}]*)\}/m) { |name, body| structs[name] = body }

# A field the Ruby would rewrite: it holds an Emittable, or a list of them.
# Optional fields are included -- Ruby's `value.is_a?(Emittable)` is false for
# nil, so a nil field is skipped, which an EXISTS guard reproduces.
def classify(type)
  t = type.strip
  return :list if t =~ /\A\??\[\]Emittable(@\w+)?\z/
  return :one if t =~ /\A\??Emittable(@\w+)?\z/

  nil
end

arms = []
variants.each do |variant, payload|
  body = structs[payload] or next
  fields = body.split(',').map(&:strip).reject(&:empty?).filter_map do |decl|
    name, type = decl.split(':', 2)
    next unless name && type

    kind = classify(type)
    kind ? [name.strip, kind, type.strip.start_with?('?')] : nil
  end
  next if fields.empty?

  lines = ["  IF node IS_A #{payload} AS rtoc_v THEN", "    MUTABLE rtoc_m = COPY rtoc_v;"]
  fields.each do |fname, kind, optional|
    rewrite = lambda do |expr|
      "castPromotableFsmValueToEmittable(emit__rewrite_promoted_fsm_node(" \
        "PromotableFsmValue{ Emittable: COPY #{expr} }, promoted_names, id))"
    end
    if kind == :one && !optional
      lines << "    rtoc_m.#{fname} = #{rewrite.call("rtoc_m.#{fname}")};"
    elsif kind == :one
      lines << "    IF rtoc_m.#{fname} EXISTS AS rtoc_f THEN"
      lines << "      rtoc_m.#{fname} = #{rewrite.call('rtoc_f')};"
      lines << '    END'
    else
      inner = optional ? "(rtoc_m.#{fname} OR_ELSE List[])" : "rtoc_m.#{fname}"
      lines << "    MUTABLE rtoc_#{fname}_out: []Emittable = List[];"
      lines << "    FOR rtoc_item IN #{inner} DO"
      lines << "      &rtoc_#{fname}_out.append(#{rewrite.call('rtoc_item')});"
      lines << '    END'
      lines << "    rtoc_m.#{fname} = rtoc_#{fname}_out;"
    end
  end
  lines << "    node = Emittable{ #{variant}: COPY rtoc_m };"
  lines << '    RETURN;'
  lines << '  END'
  arms.concat(lines)
end

fn = [
  '# GENERATED by tools/gen_fsm_struct_rewriter.rb -- do not edit by hand.',
  '# emit.rb:1058 walks a node\'s fields with Struct#members reflection and',
  '# rewrites every one holding an Emittable or a list of them. CLEAR has no',
  '# runtime reflection, so the walk is spelled out per variant, exactly as the',
  '# read-side emittable__child_exprs dispatcher in mir.clear already is.',
  'PRIVATE FN emit__rewrite_promoted_fsm_struct_fields_mut(MUTABLE node: Emittable, promoted_names: []String, id: Int64) RETURNS Void ->',
  *arms,
  '  NIL;',
  'END',
].join("\n")

puts fn
warn "generated #{arms.count { |l| l.start_with?('  IF node IS_A') }} variant arms"
